//! Go code generator implementation.
//!
//! Generates Go source files from Themis contracts:
//! - `{service}_types.go` - Type definitions
//! - `{service}_handlers.go` - Handler interfaces

// Allow some pedantic clippy lints that are acceptable in code generators
#![allow(clippy::too_many_lines)]

use heck::{ToSnakeCase, ToUpperCamelCase};
use std::fmt::Write;

use themis_core::operation::ParameterLocation;
use themis_core::{Contract, Operation};

use crate::config::GeneratorConfig;
use crate::error::CodegenResult;
use crate::traits::{CodeGenerator, GeneratedCode, GeneratedFile};

use super::types::GoTypeGenerator;

/// Go code generator.
///
/// Generates Go source files from Themis contracts including:
/// - Structs with JSON tags
/// - Handler interfaces
/// - Request context types
/// - Error types
#[derive(Debug, Clone)]
pub struct GoGenerator {
    /// Configuration for code generation.
    config: GeneratorConfig,
}

impl Default for GoGenerator {
    fn default() -> Self {
        Self::new(GeneratorConfig::default())
    }
}

impl GoGenerator {
    /// Creates a new Go generator with the given configuration.
    #[must_use]
    pub const fn new(config: GeneratorConfig) -> Self {
        Self { config }
    }

    /// Creates a new Go generator with default configuration.
    #[must_use]
    pub fn with_defaults() -> Self {
        Self::new(GeneratorConfig::default())
    }

    /// Gets the package name for the contract.
    fn get_package_name(&self, contract: &Contract) -> String {
        self.config
            .module_name
            .clone()
            .unwrap_or_else(|| sanitize_package_name(&contract.metadata.service_name))
    }

    /// Generates the types file content.
    fn generate_types_file(&self, contract: &Contract) -> String {
        let package_name = self.get_package_name(contract);
        let type_gen = GoTypeGenerator::new(package_name);
        type_gen.generate_types(&contract.schemas)
    }

    /// Generates the handlers file content.
    fn generate_handlers_file(&self, contract: &Contract) -> String {
        let package_name = self.get_package_name(contract);
        let mut output = String::new();

        // File header
        output.push_str(&Self::generate_header(contract));

        // Package declaration
        let _ = writeln!(output, "package {package_name}\n");

        // Imports
        output.push_str("import (\n");
        output.push_str("\t\"context\"\n");
        output.push_str("\t\"net/http\"\n");
        output.push_str(")\n\n");

        // Request context
        output.push_str(&Self::generate_request_context());

        // Error types
        output.push_str(&Self::generate_error_types());

        // Handler interface
        output.push_str(&Self::generate_handler_interface(contract));

        output
    }

    /// Generates file header comment.
    fn generate_header(contract: &Contract) -> String {
        format!(
            "// Code generated by themis-codegen. DO NOT EDIT.\n// Contract: {} v{}\n\n",
            contract.metadata.service_name, contract.version
        )
    }

    /// Generates the RequestContext struct.
    fn generate_request_context() -> String {
        r"// RequestContext contains request metadata.
type RequestContext struct {
	// Ctx is the request context.
	Ctx context.Context
	// Headers contains HTTP headers.
	Headers http.Header
	// PathParams contains path parameters.
	PathParams map[string]string
	// QueryParams contains query parameters.
	QueryParams map[string][]string
	// UserID is the authenticated user ID, if any.
	UserID *string
}

// NewRequestContext creates a new RequestContext.
func NewRequestContext(ctx context.Context) *RequestContext {
	return &RequestContext{
		Ctx:         ctx,
		Headers:     make(http.Header),
		PathParams:  make(map[string]string),
		QueryParams: make(map[string][]string),
	}
}

"
        .to_string()
    }

    /// Generates the error types.
    fn generate_error_types() -> String {
        r#"// ErrorCode represents an API error code.
type ErrorCode string

const (
	ErrorCodeBadRequest     ErrorCode = "bad_request"
	ErrorCodeUnauthorized   ErrorCode = "unauthorized"
	ErrorCodeForbidden      ErrorCode = "forbidden"
	ErrorCodeNotFound       ErrorCode = "not_found"
	ErrorCodeConflict       ErrorCode = "conflict"
	ErrorCodeInternalError  ErrorCode = "internal_error"
)

// APIError represents an API error.
type APIError struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
	Details any       `json:"details,omitempty"`
}

// Error implements the error interface.
func (e *APIError) Error() string {
	return e.Message
}

// NewAPIError creates a new API error.
func NewAPIError(code ErrorCode, message string) *APIError {
	return &APIError{
		Code:    code,
		Message: message,
	}
}

// WithDetails adds details to the error.
func (e *APIError) WithDetails(details any) *APIError {
	e.Details = details
	return e
}

"#
        .to_string()
    }

    /// Generates the handler interface.
    fn generate_handler_interface(contract: &Contract) -> String {
        let mut output = String::new();

        // Interface for each operation
        let service_name = contract.metadata.service_name.to_upper_camel_case();

        let _ = writeln!(
            output,
            "// {service_name}Handler defines the handler interface for the {} API.",
            contract.metadata.service_name
        );
        let _ = writeln!(output, "type {service_name}Handler interface {{");

        for (op_id, operation) in &contract.operations {
            let method_name = op_id.to_upper_camel_case();

            // Method comment
            if let Some(desc) = &operation.description {
                let _ = writeln!(output, "\t// {method_name} {desc}");
            }

            // Generate request/response types based on operation
            let request_type = format!("{method_name}Request");
            let response_type = format!("{method_name}Response");

            let _ = writeln!(
                output,
                "\t{method_name}(ctx *RequestContext, req *{request_type}) (*{response_type}, error)"
            );
        }

        output.push_str("}\n\n");

        // Generate request/response structs for each operation
        for (op_id, operation) in &contract.operations {
            output.push_str(&Self::generate_operation_types(op_id, operation));
        }

        output
    }

    /// Generates request/response types for an operation.
    fn generate_operation_types(op_id: &str, operation: &Operation) -> String {
        let mut output = String::new();
        let method_name = op_id.to_upper_camel_case();

        // Request struct
        let _ = writeln!(
            output,
            "// {method_name}Request is the request for {op_id}."
        );
        let _ = writeln!(output, "type {method_name}Request struct {{");

        // Add parameters
        for param in &operation.parameters {
            let field_name = param.name.to_upper_camel_case();
            let field_type = schema_to_go_type(&param.schema);
            let json_tag = if param.required {
                format!("`json:\"{}\"`", param.name)
            } else {
                format!("`json:\"{},omitempty\"`", param.name)
            };

            // Add comment about parameter location
            let location_str = match param.location {
                ParameterLocation::Path => "path",
                ParameterLocation::Query => "query",
                ParameterLocation::Header => "header",
                ParameterLocation::Cookie => "cookie",
            };
            let _ = writeln!(output, "\t// {field_name} is a {location_str} parameter.");

            if param.required {
                let _ = writeln!(output, "\t{field_name} {field_type} {json_tag}");
            } else {
                let _ = writeln!(output, "\t{field_name} *{field_type} {json_tag}");
            }
        }

        // Add body field if present
        if let Some(body) = &operation.request_body {
            // Get the first content type's schema
            if let Some(media) = body.content.values().next() {
                let body_type = schema_to_go_type(&media.schema);
                let _ = writeln!(
                    output,
                    "\t// Body is the request body.\n\tBody {body_type} `json:\"body\"`"
                );
            }
        }

        output.push_str("}\n\n");

        // Response struct
        let _ = writeln!(
            output,
            "// {method_name}Response is the response for {op_id}."
        );
        let _ = writeln!(output, "type {method_name}Response struct {{");

        // Find success response (2xx)
        for (status_code, response) in &operation.responses {
            if status_code.starts_with('2') {
                if let Some(media) = response.content.values().next() {
                    let data_type = schema_to_go_type(&media.schema);
                    let _ = writeln!(
                        output,
                        "\t// Data is the response data.\n\tData {data_type} `json:\"data\"`"
                    );
                }
                break;
            }
        }

        output.push_str("}\n\n");

        output
    }
}

impl CodeGenerator for GoGenerator {
    fn language_name(&self) -> &'static str {
        "Go"
    }

    fn file_extension(&self) -> &'static str {
        "go"
    }

    fn generate(&self, contract: &Contract) -> CodegenResult<GeneratedCode> {
        let mut output = GeneratedCode::new();
        let service_name = contract.metadata.service_name.to_snake_case();

        // Types file
        let types_content = self.generate_types_file(contract);
        output.add_file(GeneratedFile::new(
            format!("{service_name}_types.go"),
            types_content,
        ));

        // Handlers file
        let handlers_content = self.generate_handlers_file(contract);
        output.add_file(GeneratedFile::new(
            format!("{service_name}_handlers.go"),
            handlers_content,
        ));

        Ok(output)
    }

    fn config(&self) -> &GeneratorConfig {
        &self.config
    }
}

/// Sanitizes a string for use as a Go package name.
fn sanitize_package_name(s: &str) -> String {
    s.to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}

/// Converts a Themis schema to a Go type string (simplified version).
fn schema_to_go_type(schema: &themis_core::schema::Schema) -> String {
    use themis_core::schema::Schema;

    match schema {
        Schema::String(s) => match s.format.as_deref() {
            Some("date-time" | "date") => "time.Time".to_string(),
            Some("binary" | "byte") => "[]byte".to_string(),
            _ => "string".to_string(),
        },
        Schema::Integer(i) => match i.format.as_deref() {
            Some("int32") => "int32".to_string(),
            _ => "int64".to_string(),
        },
        Schema::Number(n) => match n.format.as_deref() {
            Some("float") => "float32".to_string(),
            _ => "float64".to_string(),
        },
        Schema::Boolean(_) => "bool".to_string(),
        Schema::Null | Schema::OneOf(_) | Schema::AllOf(_) | Schema::AnyOf(_) => {
            "interface{}".to_string()
        }
        Schema::Array(arr) => {
            let items = schema_to_go_type(&arr.items);
            format!("[]{items}")
        }
        Schema::Object(_) => "map[string]interface{}".to_string(),
        Schema::Ref(r) => r
            .reference
            .rsplit('/')
            .next()
            .map_or_else(|| "interface{}".to_string(), ToUpperCamelCase::to_upper_camel_case),
        Schema::Enum(_) => "string".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use indexmap::IndexMap;
    use std::collections::HashMap;
    use themis_core::contract::{ContractFormat, ContractMetadata};
    use themis_core::operation::{MediaType, Parameter, ParameterLocation, RequestBody, Response};
    use themis_core::schema::{IntegerSchema, ObjectSchema, RefSchema, Schema, StringSchema};
    use themis_core::version::Version;

    fn create_test_contract() -> Contract {
        let mut schemas = IndexMap::new();
        let mut properties = IndexMap::new();
        properties.insert("id".to_string(), Schema::Integer(IntegerSchema::default()));
        properties.insert("name".to_string(), Schema::String(StringSchema::default()));

        schemas.insert(
            "User".to_string(),
            Schema::Object(ObjectSchema {
                properties,
                required: vec!["id".to_string()],
                ..Default::default()
            }),
        );

        let mut operations = HashMap::new();

        // Get user operation
        let mut get_user = Operation::new("get_user");
        get_user.method = Some(themis_core::operation::HttpMethod::Get);
        get_user.path = Some("/users/{id}".to_string());
        get_user.summary = Some("Get a user by ID".to_string());
        get_user.description = Some("retrieves a user by their unique ID.".to_string());
        get_user.parameters = vec![Parameter {
            name: "id".to_string(),
            location: ParameterLocation::Path,
            required: true,
            deprecated: false,
            schema: Schema::Integer(IntegerSchema::default()),
            description: Some("User ID".to_string()),
        }];

        let mut get_user_responses = HashMap::new();
        let mut get_user_content = HashMap::new();
        get_user_content.insert(
            "application/json".to_string(),
            MediaType {
                schema: Schema::Ref(RefSchema {
                    reference: "#/components/schemas/User".to_string(),
                }),
            },
        );
        get_user_responses.insert(
            "200".to_string(),
            Response {
                description: "Success".to_string(),
                content: get_user_content,
                headers: HashMap::new(),
            },
        );
        get_user.responses = get_user_responses;
        get_user.tags = vec!["users".to_string()];

        operations.insert("get_user".to_string(), get_user);

        // Create user operation
        let mut create_user = Operation::new("create_user");
        create_user.method = Some(themis_core::operation::HttpMethod::Post);
        create_user.path = Some("/users".to_string());
        create_user.summary = Some("Create a user".to_string());
        create_user.description = Some("creates a new user.".to_string());

        let mut create_body_content = HashMap::new();
        create_body_content.insert(
            "application/json".to_string(),
            MediaType {
                schema: Schema::Ref(RefSchema {
                    reference: "#/components/schemas/User".to_string(),
                }),
            },
        );
        create_user.request_body = Some(RequestBody {
            required: true,
            description: Some("User data".to_string()),
            content: create_body_content,
        });

        let mut create_user_responses = HashMap::new();
        let mut create_user_content = HashMap::new();
        create_user_content.insert(
            "application/json".to_string(),
            MediaType {
                schema: Schema::Ref(RefSchema {
                    reference: "#/components/schemas/User".to_string(),
                }),
            },
        );
        create_user_responses.insert(
            "201".to_string(),
            Response {
                description: "Created".to_string(),
                content: create_user_content,
                headers: HashMap::new(),
            },
        );
        create_user.responses = create_user_responses;
        create_user.tags = vec!["users".to_string()];

        operations.insert("create_user".to_string(), create_user);

        Contract {
            format: ContractFormat::OpenApi,
            version: Version::new(1, 0, 0),
            metadata: ContractMetadata {
                service_name: "users-api".to_string(),
                description: Some("User management API".to_string()),
                owner: Some("platform-team".to_string()),
                repository: None,
                documentation_url: None,
            },
            operations,
            schemas,
            security_schemes: HashMap::new(),
        }
    }

    #[test]
    fn test_language_name() {
        let gen = GoGenerator::with_defaults();
        assert_eq!(gen.language_name(), "Go");
    }

    #[test]
    fn test_file_extension() {
        let gen = GoGenerator::with_defaults();
        assert_eq!(gen.file_extension(), "go");
    }

    #[test]
    fn test_generate_basic_contract() {
        let gen = GoGenerator::with_defaults();
        let contract = create_test_contract();

        let output = gen.generate(&contract).unwrap();

        assert_eq!(output.files.len(), 2);
        assert!(output.get_file("users_api_types.go").is_some());
        assert!(output.get_file("users_api_handlers.go").is_some());
    }

    #[test]
    fn test_generated_types_file() {
        let gen = GoGenerator::with_defaults();
        let contract = create_test_contract();

        let output = gen.generate(&contract).unwrap();
        let types_file = output.get_file("users_api_types.go").unwrap();

        assert!(types_file.content.contains("package users_api"));
        assert!(types_file.content.contains("type User struct {"));
        assert!(types_file.content.contains("ID int64 `json:\"id\"`"));
    }

    #[test]
    fn test_generated_handlers_file() {
        let gen = GoGenerator::with_defaults();
        let contract = create_test_contract();

        let output = gen.generate(&contract).unwrap();
        let handlers_file = output.get_file("users_api_handlers.go").unwrap();

        assert!(handlers_file.content.contains("package users_api"));
        assert!(handlers_file
            .content
            .contains("type UsersApiHandler interface {"));
    }

    #[test]
    fn test_request_context_generation() {
        let ctx = GoGenerator::generate_request_context();

        assert!(ctx.contains("type RequestContext struct {"));
        assert!(ctx.contains("Ctx context.Context"));
        assert!(ctx.contains("Headers http.Header"));
        assert!(ctx.contains("PathParams map[string]string"));
        assert!(ctx.contains("QueryParams map[string][]string"));
        assert!(ctx.contains("func NewRequestContext"));
    }

    #[test]
    fn test_error_types_generation() {
        let errors = GoGenerator::generate_error_types();

        assert!(errors.contains("type ErrorCode string"));
        assert!(errors.contains("ErrorCodeBadRequest"));
        assert!(errors.contains("ErrorCodeNotFound"));
        assert!(errors.contains("type APIError struct {"));
        assert!(errors.contains("func (e *APIError) Error() string"));
        assert!(errors.contains("func NewAPIError"));
    }

    #[test]
    fn test_custom_module_name() {
        let config = GeneratorConfig {
            module_name: Some("mypackage".to_string()),
            ..Default::default()
        };
        let gen = GoGenerator::new(config);
        let contract = create_test_contract();

        let output = gen.generate(&contract).unwrap();
        let types_file = output.get_file("users_api_types.go").unwrap();

        assert!(types_file.content.contains("package mypackage"));
    }

    #[test]
    fn test_sanitize_package_name() {
        assert_eq!(sanitize_package_name("Users API"), "users_api");
        assert_eq!(sanitize_package_name("My-Service"), "my_service");
        assert_eq!(sanitize_package_name("test123"), "test123");
    }
}
