//! TypeScript code generator.

// Allow some pedantic clippy lints that are acceptable in generated code
#![allow(clippy::missing_const_for_fn)]
#![allow(clippy::for_kv_map)]
#![allow(clippy::unused_self)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::manual_map)]

use crate::config::GeneratorConfig;
use crate::error::{CodegenError, CodegenResult};
use crate::traits::{CodeGenerator, GeneratedCode, GeneratedFile};
use crate::typescript::types::{format_jsdoc, TypeScriptTypeGenerator};
use heck::{ToLowerCamelCase, ToUpperCamelCase};
use std::fmt::Write;
use themis_core::operation::ParameterLocation;
use themis_core::{Contract, Operation};

/// TypeScript code generator.
///
/// Generates TypeScript interfaces, fetch clients, and Express handler types
/// from Themis contracts.
pub struct TypeScriptGenerator {
    config: GeneratorConfig,
}

impl TypeScriptGenerator {
    /// Creates a new TypeScript generator with the given configuration.
    pub fn new(config: GeneratorConfig) -> Self {
        Self { config }
    }

    /// Generates the types file (interfaces).
    fn generate_types_file(&self, contract: &Contract) -> CodegenResult<String> {
        let mut type_gen = TypeScriptTypeGenerator::new(&self.config);

        let mut output = String::new();

        // Header
        output.push_str("// Auto-generated by themis-codegen. DO NOT EDIT.\n");
        let _ = writeln!(
            output,
            "// Contract: {} v{}\n",
            contract.metadata.service_name, contract.version
        );

        // Generate schema types
        let types = type_gen.generate_types(&contract.schemas)?;
        output.push_str(&types);

        // Generate request/response types for operations
        output.push_str("\n// Request/Response types\n\n");
        for (_, op) in &contract.operations {
            output.push_str(&self.generate_request_type(op, &type_gen)?);
            output.push('\n');
            output.push_str(&self.generate_response_type(op, &type_gen)?);
            output.push('\n');
        }

        // Generate error types
        output.push_str("// Error types\n\n");
        output.push_str(&self.generate_error_types(contract)?);

        Ok(output)
    }

    /// Generates a request type for an operation.
    fn generate_request_type(
        &self,
        op: &Operation,
        type_gen: &TypeScriptTypeGenerator,
    ) -> CodegenResult<String> {
        let mut output = String::new();
        let type_name = format!("{}Request", op.operation_id.to_upper_camel_case());

        if self.config.include_docs {
            if let Some(desc) = &op.description {
                output.push_str(&format_jsdoc(
                    &format!("Request for {}.\n\n{}", op.operation_id, desc),
                    0,
                ));
            } else {
                output.push_str(&format_jsdoc(
                    &format!("Request for {}.", op.operation_id),
                    0,
                ));
            }
        }

        let _ = writeln!(output, "export interface {type_name} {{");

        // Path parameters
        for param in &op.parameters {
            if param.location == ParameterLocation::Path {
                let ts_name = param.name.to_lower_camel_case();
                let ts_type = type_gen.schema_to_ts_type(&param.schema)?;

                if self.config.include_docs {
                    if let Some(desc) = &param.description {
                        output.push_str(&format_jsdoc(desc, 1));
                    }
                }
                let _ = writeln!(output, "  {ts_name}: {ts_type};");
            }
        }

        // Query parameters
        for param in &op.parameters {
            if param.location == ParameterLocation::Query {
                let ts_name = param.name.to_lower_camel_case();
                let ts_type = type_gen.schema_to_ts_type(&param.schema)?;
                let optional = if param.required { "" } else { "?" };

                if self.config.include_docs {
                    if let Some(desc) = &param.description {
                        output.push_str(&format_jsdoc(desc, 1));
                    }
                }
                let _ = writeln!(output, "  {ts_name}{optional}: {ts_type};");
            }
        }

        // Request body
        if let Some(body) = &op.request_body {
            // Get the schema from the JSON content type
            if let Some(media_type) = body.content.get("application/json") {
                let ts_type = type_gen.schema_to_ts_type(&media_type.schema)?;
                if self.config.include_docs {
                    output.push_str(&format_jsdoc("Request body.", 1));
                }
                let _ = writeln!(output, "  body: {ts_type};");
            }
        }

        output.push_str("}\n");
        Ok(output)
    }

    /// Generates a response type for an operation.
    fn generate_response_type(
        &self,
        op: &Operation,
        type_gen: &TypeScriptTypeGenerator,
    ) -> CodegenResult<String> {
        let mut output = String::new();
        let type_name = format!("{}Response", op.operation_id.to_upper_camel_case());

        if self.config.include_docs {
            output.push_str(&format_jsdoc(
                &format!("Response from {}.", op.operation_id),
                0,
            ));
        }

        // Find success responses and get their schemas
        let success_schemas: Vec<_> = op
            .responses
            .iter()
            .filter(|(code, _)| code.starts_with('2'))
            .filter_map(|(_, response)| {
                // Get schema from application/json content
                response
                    .content
                    .get("application/json")
                    .map(|media| &media.schema)
            })
            .collect();

        if success_schemas.len() == 1 {
            let ts_type = type_gen.schema_to_ts_type(success_schemas[0])?;
            let _ = writeln!(output, "export type {type_name} = {ts_type};\n");
        } else if success_schemas.is_empty() {
            // No response body (e.g., 204)
            let _ = writeln!(output, "export type {type_name} = void;\n");
        } else {
            // Multiple success responses - create a union
            let variants: Vec<String> = success_schemas
                .iter()
                .filter_map(|schema| type_gen.schema_to_ts_type(schema).ok())
                .collect();
            let _ = writeln!(
                output,
                "export type {type_name} = {};\n",
                variants.join(" | ")
            );
        }

        Ok(output)
    }

    /// Generates error types for the service.
    fn generate_error_types(&self, contract: &Contract) -> CodegenResult<String> {
        let mut output = String::new();
        let service_name = contract.metadata.service_name.to_upper_camel_case();

        // Generate standard error interface
        output.push_str(&format_jsdoc("Base error interface for service errors.", 0));
        let _ = writeln!(output, "export interface {service_name}Error {{");
        output.push_str("  code: string;\n");
        output.push_str("  message: string;\n");
        output.push_str("  details?: Record<string, unknown>;\n");
        output.push_str("  requestId?: string;\n");
        output.push_str("  timestamp?: string;\n");
        output.push_str("}\n\n");

        // Generate specific error types from error responses
        let mut error_types = Vec::new();

        // BadRequest error
        error_types.push(format!("{service_name}BadRequestError"));
        output.push_str(&format_jsdoc("Bad request error (400).", 0));
        let _ = writeln!(
            output,
            "export interface {service_name}BadRequestError extends {service_name}Error {{"
        );
        output.push_str("  code: \"BAD_REQUEST\" | \"VALIDATION_FAILED\";\n");
        output.push_str("  fieldErrors?: Array<{ field: string; message: string }>;\n");
        output.push_str("}\n\n");

        // Unauthorized error
        error_types.push(format!("{service_name}UnauthorizedError"));
        output.push_str(&format_jsdoc("Unauthorized error (401).", 0));
        let _ = writeln!(
            output,
            "export interface {service_name}UnauthorizedError extends {service_name}Error {{"
        );
        output.push_str("  code: \"UNAUTHENTICATED\" | \"INVALID_TOKEN\";\n");
        output.push_str("}\n\n");

        // Forbidden error
        error_types.push(format!("{service_name}ForbiddenError"));
        output.push_str(&format_jsdoc("Forbidden error (403).", 0));
        let _ = writeln!(
            output,
            "export interface {service_name}ForbiddenError extends {service_name}Error {{"
        );
        output.push_str("  code: \"PERMISSION_DENIED\" | \"POLICY_DENIED\";\n");
        output.push_str("}\n\n");

        // NotFound error
        error_types.push(format!("{service_name}NotFoundError"));
        output.push_str(&format_jsdoc("Not found error (404).", 0));
        let _ = writeln!(
            output,
            "export interface {service_name}NotFoundError extends {service_name}Error {{"
        );
        output.push_str("  code: \"NOT_FOUND\";\n");
        output.push_str("  resource?: string;\n");
        output.push_str("}\n\n");

        // InternalError
        error_types.push(format!("{service_name}InternalError"));
        output.push_str(&format_jsdoc("Internal server error (500).", 0));
        let _ = writeln!(
            output,
            "export interface {service_name}InternalError extends {service_name}Error {{"
        );
        output.push_str("  code: \"INTERNAL_ERROR\";\n");
        output.push_str("  traceId?: string;\n");
        output.push_str("}\n\n");

        // Union type of all errors
        output.push_str(&format_jsdoc("Union of all service errors.", 0));
        let _ = writeln!(
            output,
            "export type {service_name}ServiceError = {};",
            error_types.join(" | ")
        );
        output.push('\n');

        Ok(output)
    }

    /// Generates the fetch client file.
    fn generate_client_file(&self, contract: &Contract) -> CodegenResult<String> {
        let mut output = String::new();
        let service_name = contract.metadata.service_name.to_upper_camel_case();

        // Header
        output.push_str("// Auto-generated by themis-codegen. DO NOT EDIT.\n");
        let _ = writeln!(
            output,
            "// Contract: {} v{}\n",
            contract.metadata.service_name, contract.version
        );

        // Imports
        output.push_str("import type {\n");
        for (_, op) in &contract.operations {
            let request_type = format!("{}Request", op.operation_id.to_upper_camel_case());
            let response_type = format!("{}Response", op.operation_id.to_upper_camel_case());
            let _ = writeln!(output, "  {request_type},");
            let _ = writeln!(output, "  {response_type},");
        }
        let _ = writeln!(output, "  {service_name}ServiceError,");
        output.push_str("} from './types';\n\n");

        // Client options interface
        output.push_str(&format_jsdoc("Options for the API client.", 0));
        let _ = writeln!(output, "export interface {service_name}ClientOptions {{");
        output.push_str("  /** Base URL for the API */\n");
        output.push_str("  baseUrl: string;\n");
        output.push_str("  /** Request headers to include with every request */\n");
        output.push_str("  headers?: Record<string, string>;\n");
        output.push_str("  /** Custom fetch implementation */\n");
        output.push_str("  fetch?: typeof fetch;\n");
        output.push_str("}\n\n");

        // Result type
        output.push_str(&format_jsdoc("Result type for API calls.", 0));
        let _ = writeln!(output, "export type {service_name}Result<T> =");
        output.push_str("  | { ok: true; data: T }\n");
        let _ = writeln!(
            output,
            "  | {{ ok: false; error: {service_name}ServiceError }};\n"
        );

        // Client interface
        output.push_str(&format_jsdoc(
            &format!("Client interface for {}.", contract.metadata.service_name),
            0,
        ));
        let _ = writeln!(output, "export interface {service_name}Client {{");
        for (_, op) in &contract.operations {
            let method_name = op.operation_id.to_lower_camel_case();
            let request_type = format!("{}Request", op.operation_id.to_upper_camel_case());
            let response_type = format!("{}Response", op.operation_id.to_upper_camel_case());

            if self.config.include_docs {
                if let Some(summary) = &op.summary {
                    output.push_str(&format_jsdoc(summary, 1));
                }
            }
            let _ = writeln!(
                output,
                "  {method_name}(request: {request_type}): Promise<{service_name}Result<{response_type}>>;"
            );
        }
        output.push_str("}\n\n");

        // Client implementation
        output.push_str(&format_jsdoc(
            &format!("Creates a {} client.", contract.metadata.service_name),
            0,
        ));
        let _ = writeln!(
            output,
            "export function create{service_name}Client(options: {service_name}ClientOptions): {service_name}Client {{"
        );
        output.push_str("  const fetchFn = options.fetch ?? fetch;\n\n");

        output.push_str("  async function request<T>(\n");
        output.push_str("    method: string,\n");
        output.push_str("    path: string,\n");
        output.push_str("    body?: unknown\n");
        let _ = writeln!(output, "  ): Promise<{service_name}Result<T>> {{");
        output.push_str("    try {\n");
        output.push_str("      const response = await fetchFn(`${options.baseUrl}${path}`, {\n");
        output.push_str("        method,\n");
        output.push_str("        headers: {\n");
        output.push_str("          'Content-Type': 'application/json',\n");
        output.push_str("          ...options.headers,\n");
        output.push_str("        },\n");
        output.push_str("        body: body ? JSON.stringify(body) : undefined,\n");
        output.push_str("      });\n\n");
        output.push_str("      if (!response.ok) {\n");
        output.push_str("        const error = await response.json();\n");
        output.push_str("        return { ok: false, error };\n");
        output.push_str("      }\n\n");
        output.push_str("      if (response.status === 204) {\n");
        output.push_str("        return { ok: true, data: undefined as T };\n");
        output.push_str("      }\n\n");
        output.push_str("      const data = await response.json();\n");
        output.push_str("      return { ok: true, data };\n");
        output.push_str("    } catch (error) {\n");
        output.push_str("      return {\n");
        output.push_str("        ok: false,\n");
        output.push_str("        error: {\n");
        output.push_str("          code: 'INTERNAL_ERROR',\n");
        output.push_str(
            "          message: error instanceof Error ? error.message : 'Unknown error',\n",
        );
        output.push_str("        },\n");
        output.push_str("      };\n");
        output.push_str("    }\n");
        output.push_str("  }\n\n");

        output.push_str("  return {\n");
        for (_, op) in &contract.operations {
            let method_name = op.operation_id.to_lower_camel_case();
            let request_type = format!("{}Request", op.operation_id.to_upper_camel_case());
            let response_type = format!("{}Response", op.operation_id.to_upper_camel_case());

            let _ = writeln!(
                output,
                "    async {method_name}(req: {request_type}): Promise<{service_name}Result<{response_type}>> {{"
            );

            // Build the path with parameter substitution
            let path = self.build_path_expression(op);
            let _ = writeln!(output, "      const path = {path};");

            // Add query parameters if any
            let query_params: Vec<_> = op
                .parameters
                .iter()
                .filter(|p| p.location == ParameterLocation::Query)
                .collect();

            if query_params.is_empty() {
                output.push_str("      const fullPath = path;\n");
            } else {
                output.push_str("      const params = new URLSearchParams();\n");
                for param in query_params {
                    let ts_name = param.name.to_lower_camel_case();
                    if param.required {
                        let _ = writeln!(
                            output,
                            "      params.set('{}', String(req.{ts_name}));",
                            param.name
                        );
                    } else {
                        let _ = writeln!(
                            output,
                            "      if (req.{ts_name} !== undefined) params.set('{}', String(req.{ts_name}));",
                            param.name
                        );
                    }
                }
                output.push_str("      const queryString = params.toString();\n");
                // Note: Uses JavaScript template literal syntax, not Rust format
                output.push_str(
                    "      const fullPath = queryString ? `${{path}}?${{queryString}}` : path;\n",
                );
            }

            let http_method = op
                .method
                .as_ref()
                .map_or_else(|| "GET".to_string(), |m| m.to_string().to_uppercase());
            let body = if op.request_body.is_some() {
                "req.body"
            } else {
                "undefined"
            };

            let _ = writeln!(
                output,
                "      return request<{response_type}>('{http_method}', fullPath, {body});"
            );
            output.push_str("    },\n\n");
        }
        output.push_str("  };\n");
        output.push_str("}\n");

        Ok(output)
    }

    /// Builds a path expression with template literal substitution.
    fn build_path_expression(&self, op: &Operation) -> String {
        let mut path = op.path.clone().unwrap_or_else(|| "/".to_string());

        // Replace path parameters with template expressions
        for param in &op.parameters {
            if param.location == ParameterLocation::Path {
                let placeholder = format!("{{{}}}", param.name);
                let ts_expr = format!("${{req.{}}}", param.name.to_lower_camel_case());
                path = path.replace(&placeholder, &ts_expr);
            }
        }

        format!("`{path}`")
    }

    /// Generates the Express handler types file.
    fn generate_handlers_file(&self, contract: &Contract) -> CodegenResult<String> {
        let mut output = String::new();
        let service_name = contract.metadata.service_name.to_upper_camel_case();

        // Header
        output.push_str("// Auto-generated by themis-codegen. DO NOT EDIT.\n");
        let _ = writeln!(
            output,
            "// Contract: {} v{}\n",
            contract.metadata.service_name, contract.version
        );

        // Imports
        output
            .push_str("import type { Router, Request, Response, NextFunction } from 'express';\n");
        output.push_str("import type {\n");
        for (_, op) in &contract.operations {
            let request_type = format!("{}Request", op.operation_id.to_upper_camel_case());
            let response_type = format!("{}Response", op.operation_id.to_upper_camel_case());
            let _ = writeln!(output, "  {request_type},");
            let _ = writeln!(output, "  {response_type},");
        }
        output.push_str("} from './types';\n\n");

        // Request context (similar to Rust RequestContext)
        output.push_str(&format_jsdoc("Request context passed to handlers.", 0));
        output.push_str("export interface RequestContext {\n");
        output.push_str("  /** Unique request ID */\n");
        output.push_str("  requestId: string;\n");
        output.push_str("  /** Authenticated user ID (if available) */\n");
        output.push_str("  userId?: string;\n");
        output.push_str("  /** Request headers */\n");
        output.push_str("  headers: Record<string, string | undefined>;\n");
        output.push_str("}\n\n");

        // Handlers interface
        output.push_str(&format_jsdoc(
            &format!("Handler interface for {}.", contract.metadata.service_name),
            0,
        ));
        let _ = writeln!(output, "export interface {service_name}Handlers {{");
        for (_, op) in &contract.operations {
            let method_name = op.operation_id.to_lower_camel_case();
            let request_type = format!("{}Request", op.operation_id.to_upper_camel_case());
            let response_type = format!("{}Response", op.operation_id.to_upper_camel_case());

            if self.config.include_docs {
                if let Some(summary) = &op.summary {
                    output.push_str(&format_jsdoc(summary, 1));
                }
            }
            let _ = writeln!(
                output,
                "  {method_name}(ctx: RequestContext, request: {request_type}): Promise<{response_type}>;"
            );
        }
        output.push_str("}\n\n");

        // Router factory
        output.push_str(&format_jsdoc(
            &format!(
                "Creates an Express router for {}.",
                contract.metadata.service_name
            ),
            0,
        ));
        let _ = writeln!(
            output,
            "export function create{service_name}Router(handlers: {service_name}Handlers): Router {{"
        );
        output.push_str("  // Note: This requires express to be installed\n");
        output.push_str("  // eslint-disable-next-line @typescript-eslint/no-var-requires\n");
        output.push_str("  const { Router } = require('express');\n");
        output.push_str("  const router = Router();\n\n");

        for (_, op) in &contract.operations {
            let method_name = op.operation_id.to_lower_camel_case();
            let http_method = op
                .method
                .as_ref()
                .map_or_else(|| "get".to_string(), |m| m.to_string().to_lowercase());
            let express_path =
                self.path_to_express_format(&op.path.clone().unwrap_or_else(|| "/".to_string()));

            let _ = writeln!(output, "  router.{http_method}('{express_path}',");
            output.push_str("    async (req: Request, res: Response, next: NextFunction) => {\n");
            output.push_str("      try {\n");
            output.push_str("        const ctx: RequestContext = {\n");
            output.push_str(
                "          requestId: req.headers['x-request-id'] as string ?? crypto.randomUUID(),\n",
            );
            output.push_str("          userId: (req as any).userId,\n");
            output.push_str(
                "          headers: req.headers as Record<string, string | undefined>,\n",
            );
            output.push_str("        };\n\n");

            // Build request object
            output.push_str("        const request = {\n");

            // Path parameters
            for param in &op.parameters {
                if param.location == ParameterLocation::Path {
                    let ts_name = param.name.to_lower_camel_case();
                    let _ = writeln!(output, "          {ts_name}: req.params.{},", param.name);
                }
            }

            // Query parameters
            for param in &op.parameters {
                if param.location == ParameterLocation::Query {
                    let ts_name = param.name.to_lower_camel_case();
                    let _ = writeln!(
                        output,
                        "          {ts_name}: req.query.{} as string,",
                        param.name
                    );
                }
            }

            // Request body
            if op.request_body.is_some() {
                output.push_str("          body: req.body,\n");
            }

            output.push_str("        };\n\n");

            let _ = writeln!(
                output,
                "        const response = await handlers.{method_name}(ctx, request);"
            );

            // Determine status code
            let status_code = if op
                .method
                .as_ref()
                .is_some_and(|m| m.to_string() == "POST")
            {
                "201"
            } else {
                "200"
            };
            let _ = writeln!(output, "        res.status({status_code}).json(response);");
            output.push_str("      } catch (error) {\n");
            output.push_str("        next(error);\n");
            output.push_str("      }\n");
            output.push_str("    }\n");
            output.push_str("  );\n\n");
        }

        output.push_str("  return router;\n");
        output.push_str("}\n");

        Ok(output)
    }

    /// Converts OpenAPI path to Express format.
    fn path_to_express_format(&self, path: &str) -> String {
        // Convert {param} to :param
        let mut result = path.to_string();
        while let Some(start) = result.find('{') {
            if let Some(end) = result.find('}') {
                let param = &result[start + 1..end];
                result = result.replace(&format!("{{{param}}}"), &format!(":{param}"));
            } else {
                break;
            }
        }
        result
    }

    /// Generates the index file that re-exports everything.
    fn generate_index_file(&self, contract: &Contract) -> String {
        let mut output = String::new();
        let service_name = contract.metadata.service_name.to_upper_camel_case();

        output.push_str("// Auto-generated by themis-codegen. DO NOT EDIT.\n\n");
        output.push_str("export * from './types';\n");
        output.push_str("export * from './client';\n");
        output.push_str("export * from './handlers';\n\n");
        let _ = writeln!(output, "// Re-export main client factory");
        let _ = writeln!(
            output,
            "export {{ create{service_name}Client }} from './client';"
        );
        let _ = writeln!(
            output,
            "export {{ create{service_name}Router }} from './handlers';"
        );

        output
    }
}

impl CodeGenerator for TypeScriptGenerator {
    fn language_name(&self) -> &'static str {
        "TypeScript"
    }

    fn file_extension(&self) -> &'static str {
        "ts"
    }

    fn generate(&self, contract: &Contract) -> CodegenResult<GeneratedCode> {
        if contract.operations.is_empty() {
            return Err(CodegenError::EmptyContract {
                name: contract.metadata.service_name.clone(),
            });
        }

        let mut output = GeneratedCode::new();

        // Generate types file
        let types_content = self.generate_types_file(contract)?;
        output.add_file(GeneratedFile::new("types.ts", types_content));

        // Generate client file
        let client_content = self.generate_client_file(contract)?;
        output.add_file(GeneratedFile::new("client.ts", client_content));

        // Generate handlers file
        let handlers_content = self.generate_handlers_file(contract)?;
        output.add_file(GeneratedFile::new("handlers.ts", handlers_content));

        // Generate index file
        let index_content = self.generate_index_file(contract);
        output.add_file(GeneratedFile::new("index.ts", index_content));

        Ok(output)
    }

    fn config(&self) -> &GeneratorConfig {
        &self.config
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;
    use themis_core::contract::{ContractFormat, ContractMetadata};
    use themis_core::operation::{HttpMethod, MediaType, Parameter, RequestBody, Response};
    use themis_core::schema::{ObjectSchema, RefSchema, StringSchema};
    use themis_core::Schema;
    use themis_core::Version;

    fn create_test_contract() -> Contract {
        let mut schemas = HashMap::new();
        schemas.insert(
            "User".to_string(),
            Schema::Object(ObjectSchema {
                description: Some("A user in the system".to_string()),
                properties: {
                    let mut props = HashMap::new();
                    props.insert("id".to_string(), Schema::String(StringSchema::default()));
                    props.insert("email".to_string(), Schema::String(StringSchema::default()));
                    props.insert("name".to_string(), Schema::String(StringSchema::default()));
                    props
                },
                required: vec!["id".to_string(), "email".to_string()],
                additional_properties: None,
                nullable: false,
            }),
        );

        let mut operations = HashMap::new();

        // getUser operation
        let mut get_user = Operation::new("getUser");
        get_user.method = Some(HttpMethod::Get);
        get_user.path = Some("/users/{userId}".to_string());
        get_user.summary = Some("Get a user by ID".to_string());
        get_user.description = Some("Retrieves a user by their unique identifier".to_string());
        get_user.parameters = vec![Parameter {
            name: "userId".to_string(),
            location: ParameterLocation::Path,
            required: true,
            deprecated: false,
            schema: Schema::String(StringSchema::default()),
            description: Some("The user's ID".to_string()),
        }];
        get_user.responses.insert(
            "200".to_string(),
            Response {
                description: "Success".to_string(),
                content: {
                    let mut content = HashMap::new();
                    content.insert(
                        "application/json".to_string(),
                        MediaType {
                            schema: Schema::Ref(RefSchema {
                                reference: "#/components/schemas/User".to_string(),
                            }),
                        },
                    );
                    content
                },
                headers: HashMap::new(),
            },
        );
        operations.insert("getUser".to_string(), get_user);

        // createUser operation
        let mut create_user = Operation::new("createUser");
        create_user.method = Some(HttpMethod::Post);
        create_user.path = Some("/users".to_string());
        create_user.summary = Some("Create a new user".to_string());
        create_user.request_body = Some(RequestBody {
            description: None,
            required: true,
            content: {
                let mut content = HashMap::new();
                content.insert(
                    "application/json".to_string(),
                    MediaType {
                        schema: Schema::Object(ObjectSchema {
                            description: None,
                            properties: {
                                let mut props = HashMap::new();
                                props.insert(
                                    "email".to_string(),
                                    Schema::String(StringSchema::default()),
                                );
                                props.insert(
                                    "name".to_string(),
                                    Schema::String(StringSchema::default()),
                                );
                                props
                            },
                            required: vec!["email".to_string(), "name".to_string()],
                            additional_properties: None,
                            nullable: false,
                        }),
                    },
                );
                content
            },
        });
        create_user.responses.insert(
            "201".to_string(),
            Response {
                description: "Created".to_string(),
                content: {
                    let mut content = HashMap::new();
                    content.insert(
                        "application/json".to_string(),
                        MediaType {
                            schema: Schema::Ref(RefSchema {
                                reference: "#/components/schemas/User".to_string(),
                            }),
                        },
                    );
                    content
                },
                headers: HashMap::new(),
            },
        );
        operations.insert("createUser".to_string(), create_user);

        Contract {
            format: ContractFormat::OpenApi,
            version: Version::new(1, 0, 0),
            metadata: ContractMetadata {
                service_name: "users-service".to_string(),
                description: None,
                owner: None,
                repository: None,
                documentation_url: None,
            },
            schemas,
            operations,
            security_schemes: HashMap::new(),
        }
    }

    #[test]
    fn test_typescript_generator_language_name() {
        let config = GeneratorConfig::default();
        let generator = TypeScriptGenerator::new(config);
        assert_eq!(generator.language_name(), "TypeScript");
    }

    #[test]
    fn test_typescript_generator_file_extension() {
        let config = GeneratorConfig::default();
        let generator = TypeScriptGenerator::new(config);
        assert_eq!(generator.file_extension(), "ts");
    }

    #[test]
    fn test_typescript_generator_creates_files() {
        let config = GeneratorConfig::default();
        let generator = TypeScriptGenerator::new(config);
        let contract = create_test_contract();

        let result = generator.generate(&contract).unwrap();

        assert!(result.get_file("types.ts").is_some());
        assert!(result.get_file("client.ts").is_some());
        assert!(result.get_file("handlers.ts").is_some());
        assert!(result.get_file("index.ts").is_some());
    }

    #[test]
    fn test_typescript_generator_types_content() {
        let config = GeneratorConfig::default();
        let generator = TypeScriptGenerator::new(config);
        let contract = create_test_contract();

        let result = generator.generate(&contract).unwrap();
        let types_file = result.get_file("types.ts").unwrap();

        assert!(types_file.content.contains("export interface User {"));
        assert!(types_file.content.contains("id: string;"));
        assert!(types_file
            .content
            .contains("export interface GetUserRequest {"));
        assert!(types_file
            .content
            .contains("export interface CreateUserRequest {"));
    }

    #[test]
    fn test_typescript_generator_client_content() {
        let config = GeneratorConfig::default();
        let generator = TypeScriptGenerator::new(config);
        let contract = create_test_contract();

        let result = generator.generate(&contract).unwrap();
        let client_file = result.get_file("client.ts").unwrap();

        assert!(client_file
            .content
            .contains("export interface UsersServiceClient {"));
        assert!(client_file
            .content
            .contains("getUser(request: GetUserRequest)"));
        assert!(client_file
            .content
            .contains("createUser(request: CreateUserRequest)"));
        assert!(client_file
            .content
            .contains("export function createUsersServiceClient"));
    }

    #[test]
    fn test_typescript_generator_handlers_content() {
        let config = GeneratorConfig::default();
        let generator = TypeScriptGenerator::new(config);
        let contract = create_test_contract();

        let result = generator.generate(&contract).unwrap();
        let handlers_file = result.get_file("handlers.ts").unwrap();

        assert!(handlers_file
            .content
            .contains("export interface RequestContext {"));
        assert!(handlers_file
            .content
            .contains("export interface UsersServiceHandlers {"));
        assert!(handlers_file
            .content
            .contains("export function createUsersServiceRouter"));
        assert!(handlers_file
            .content
            .contains("router.get('/users/:userId'"));
        assert!(handlers_file.content.contains("router.post('/users'"));
    }

    #[test]
    fn test_typescript_generator_empty_contract_fails() {
        let config = GeneratorConfig::default();
        let generator = TypeScriptGenerator::new(config);
        let contract = Contract {
            format: ContractFormat::OpenApi,
            version: Version::new(1, 0, 0),
            metadata: ContractMetadata {
                service_name: "empty-service".to_string(),
                description: None,
                owner: None,
                repository: None,
                documentation_url: None,
            },
            schemas: HashMap::new(),
            operations: HashMap::new(),
            security_schemes: HashMap::new(),
        };

        let result = generator.generate(&contract);
        assert!(result.is_err());
    }

    #[test]
    fn test_path_to_express_format() {
        let config = GeneratorConfig::default();
        let generator = TypeScriptGenerator::new(config);

        assert_eq!(
            generator.path_to_express_format("/users/{userId}"),
            "/users/:userId"
        );
        assert_eq!(
            generator.path_to_express_format("/users/{userId}/posts/{postId}"),
            "/users/:userId/posts/:postId"
        );
        assert_eq!(generator.path_to_express_format("/users"), "/users");
    }

    #[test]
    fn test_build_path_expression() {
        let config = GeneratorConfig::default();
        let generator = TypeScriptGenerator::new(config);

        let mut op = Operation::new("getUser");
        op.method = Some(HttpMethod::Get);
        op.path = Some("/users/{userId}".to_string());
        op.parameters = vec![Parameter {
            name: "userId".to_string(),
            location: ParameterLocation::Path,
            required: true,
            deprecated: false,
            schema: Schema::String(StringSchema::default()),
            description: None,
        }];

        let result = generator.build_path_expression(&op);
        assert_eq!(result, "`/users/${req.userId}`");
    }

    #[test]
    fn test_typescript_generator_with_jsdoc() {
        let config = GeneratorConfig {
            include_docs: true,
            ..Default::default()
        };
        let generator = TypeScriptGenerator::new(config);
        let contract = create_test_contract();

        let result = generator.generate(&contract).unwrap();
        let types_file = result.get_file("types.ts").unwrap();

        // Should contain JSDoc comments
        assert!(types_file.content.contains("/** A user in the system */"));
    }

    #[test]
    fn test_typescript_generator_index_file() {
        let config = GeneratorConfig::default();
        let generator = TypeScriptGenerator::new(config);
        let contract = create_test_contract();

        let result = generator.generate(&contract).unwrap();
        let index_file = result.get_file("index.ts").unwrap();

        assert!(index_file.content.contains("export * from './types'"));
        assert!(index_file.content.contains("export * from './client'"));
        assert!(index_file.content.contains("export * from './handlers'"));
        assert!(index_file.content.contains("createUsersServiceClient"));
        assert!(index_file.content.contains("createUsersServiceRouter"));
    }
}
