//! TypeScript type generation from schemas.

// Allow some pedantic clippy lints that are acceptable in generated code
#![allow(clippy::missing_const_for_fn)]
#![allow(clippy::unused_self)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]

use crate::config::GeneratorConfig;
use crate::error::CodegenResult;
use heck::{ToLowerCamelCase, ToUpperCamelCase};
use std::collections::HashMap;
use std::fmt::Write;
use themis_core::schema::{
    AllOfSchema, AnyOfSchema, ArraySchema, EnumSchema, ObjectSchema, OneOfSchema, Schema,
};

/// Generates TypeScript type definitions from schemas.
pub struct TypeScriptTypeGenerator<'a> {
    config: &'a GeneratorConfig,
    /// Maps schema names to their generated TypeScript type names
    type_map: HashMap<String, String>,
}

impl<'a> TypeScriptTypeGenerator<'a> {
    /// Creates a new type generator.
    pub fn new(config: &'a GeneratorConfig) -> Self {
        Self {
            config,
            type_map: HashMap::new(),
        }
    }

    /// Generates TypeScript interfaces from a map of named schemas.
    pub fn generate_types(&mut self, schemas: &HashMap<String, Schema>) -> CodegenResult<String> {
        let mut output = String::new();

        // Generate header comment
        output.push_str("// Auto-generated by themis-codegen. DO NOT EDIT.\n\n");

        // First pass: register all type names
        for name in schemas.keys() {
            let ts_name = self.schema_name_to_ts_type(name);
            self.type_map.insert(name.clone(), ts_name);
        }

        // Second pass: generate types
        for (name, schema) in schemas {
            let type_code = self.generate_schema_type(name, schema)?;
            output.push_str(&type_code);
            output.push('\n');
        }

        Ok(output)
    }

    /// Generates a TypeScript type for a named schema.
    fn generate_schema_type(&self, name: &str, schema: &Schema) -> CodegenResult<String> {
        let ts_name = self.schema_name_to_ts_type(name);

        match schema {
            Schema::Object(obj) => self.generate_interface(&ts_name, obj),
            Schema::Enum(enum_schema) => Ok(self.generate_enum(&ts_name, enum_schema)),
            Schema::OneOf(one_of) => Ok(self.generate_union_type(&ts_name, one_of)),
            Schema::AllOf(all_of) => self.generate_intersection_type(&ts_name, all_of),
            Schema::AnyOf(any_of) => Ok(self.generate_any_of_union(&ts_name, any_of)),
            _ => {
                // For simple types, generate a type alias
                let inner_type = self.schema_to_ts_type(schema)?;
                Ok(format!("export type {ts_name} = {inner_type};\n"))
            }
        }
    }

    /// Generates a TypeScript interface from an object schema.
    fn generate_interface(&self, name: &str, obj: &ObjectSchema) -> CodegenResult<String> {
        let mut output = String::new();

        // JSDoc comment
        if let Some(desc) = &obj.description {
            if self.config.include_docs {
                output.push_str(&format_jsdoc(desc, 0));
            }
        }

        // Interface declaration
        let _ = writeln!(output, "export interface {name} {{");

        // Generate properties
        for (prop_name, prop_schema) in &obj.properties {
            let ts_name = prop_name.to_lower_camel_case();
            let ts_type = self.schema_to_ts_type(prop_schema)?;
            let optional = !obj.required.contains(prop_name);

            // Property JSDoc
            if self.config.include_docs {
                if let Some(desc) = prop_schema.description() {
                    output.push_str(&format_jsdoc(desc, 1));
                }
            }

            if optional {
                let _ = writeln!(output, "  {ts_name}?: {ts_type};");
            } else {
                let _ = writeln!(output, "  {ts_name}: {ts_type};");
            }
        }

        output.push_str("}\n");
        Ok(output)
    }

    /// Generates a TypeScript string literal union from an enum schema.
    fn generate_enum(&self, name: &str, enum_schema: &EnumSchema) -> String {
        let mut output = String::new();

        // JSDoc comment
        if let Some(desc) = &enum_schema.description {
            if self.config.include_docs {
                output.push_str(&format_jsdoc(desc, 0));
            }
        }

        // Generate string literal union
        let variants: Vec<String> = enum_schema
            .values
            .iter()
            .map(|v| {
                // EnumValue.value is a serde_json::Value, convert to string
                match &v.value {
                    serde_json::Value::String(s) => format!("\"{s}\""),
                    other => format!("\"{other}\""), // Numbers, bools, etc
                }
            })
            .collect();

        let _ = writeln!(output, "export type {name} = {};", variants.join(" | "));
        output
    }

    /// Generates a union type from oneOf schema.
    fn generate_union_type(&self, name: &str, one_of: &OneOfSchema) -> String {
        let mut output = String::new();

        if let Some(desc) = &one_of.description {
            if self.config.include_docs {
                output.push_str(&format_jsdoc(desc, 0));
            }
        }

        let variants: Vec<String> = one_of
            .schemas
            .iter()
            .filter_map(|s| self.schema_to_ts_type(s).ok())
            .collect();

        let _ = writeln!(output, "export type {name} = {};", variants.join(" | "));
        output
    }

    /// Generates an intersection type from allOf schema.
    fn generate_intersection_type(
        &self,
        name: &str,
        all_of: &AllOfSchema,
    ) -> CodegenResult<String> {
        let mut output = String::new();

        if let Some(desc) = &all_of.description {
            if self.config.include_docs {
                output.push_str(&format_jsdoc(desc, 0));
            }
        }

        let parts: Vec<String> = all_of
            .schemas
            .iter()
            .filter_map(|s| self.schema_to_ts_type(s).ok())
            .collect();

        let _ = writeln!(output, "export type {name} = {};", parts.join(" & "));
        Ok(output)
    }

    /// Generates a union type from anyOf schema.
    fn generate_any_of_union(&self, name: &str, any_of: &AnyOfSchema) -> String {
        let mut output = String::new();

        if let Some(desc) = &any_of.description {
            if self.config.include_docs {
                output.push_str(&format_jsdoc(desc, 0));
            }
        }

        let variants: Vec<String> = any_of
            .schemas
            .iter()
            .filter_map(|s| self.schema_to_ts_type(s).ok())
            .collect();

        let _ = writeln!(output, "export type {name} = {};", variants.join(" | "));
        output
    }

    /// Converts an OpenAPI schema name to a TypeScript type name.
    fn schema_name_to_ts_type(&self, name: &str) -> String {
        name.to_upper_camel_case()
    }

    /// Converts a schema to its TypeScript type representation.
    pub fn schema_to_ts_type(&self, schema: &Schema) -> CodegenResult<String> {
        match schema {
            Schema::String(s) => Ok(self.string_schema_to_ts_type(s)),
            Schema::Integer(_) | Schema::Number(_) => Ok("number".to_string()),
            Schema::Boolean(_) => Ok("boolean".to_string()),
            Schema::Array(arr) => self.array_schema_to_ts_type(arr),
            Schema::Object(obj) => {
                if obj.properties.is_empty() && obj.additional_properties.is_none() {
                    Ok("Record<string, unknown>".to_string())
                } else if obj.properties.is_empty() {
                    // additionalProperties case - use Record
                    if let Some(additional) = &obj.additional_properties {
                        let value_type = self.schema_to_ts_type(additional)?;
                        Ok(format!("Record<string, {value_type}>"))
                    } else {
                        Ok("Record<string, unknown>".to_string())
                    }
                } else {
                    // Inline object type
                    self.generate_inline_object(obj)
                }
            }
            Schema::Ref(r) => {
                // Extract the type name from the ref
                let type_name = r
                    .reference
                    .split('/')
                    .last()
                    .unwrap_or(&r.reference)
                    .to_upper_camel_case();
                Ok(type_name)
            }
            Schema::Enum(e) => {
                // Inline enum as string literal union
                let variants: Vec<String> = e
                    .values
                    .iter()
                    .map(|v| match &v.value {
                        serde_json::Value::String(s) => format!("\"{}\"", s),
                        other => format!("\"{}\"", other),
                    })
                    .collect();
                Ok(variants.join(" | "))
            }
            Schema::OneOf(one_of) => {
                let variants: Vec<String> = one_of
                    .schemas
                    .iter()
                    .filter_map(|s| self.schema_to_ts_type(s).ok())
                    .collect();
                Ok(variants.join(" | "))
            }
            Schema::AllOf(all_of) => {
                let parts: Vec<String> = all_of
                    .schemas
                    .iter()
                    .filter_map(|s| self.schema_to_ts_type(s).ok())
                    .collect();
                Ok(parts.join(" & "))
            }
            Schema::AnyOf(any_of) => {
                let variants: Vec<String> = any_of
                    .schemas
                    .iter()
                    .filter_map(|s| self.schema_to_ts_type(s).ok())
                    .collect();
                Ok(variants.join(" | "))
            }
            Schema::Null => Ok("null".to_string()),
        }
    }

    /// Converts a string schema to TypeScript type.
    fn string_schema_to_ts_type(&self, s: &themis_core::schema::StringSchema) -> String {
        // Check for common formats
        // All string formats map to "string" in TypeScript, but we could enhance
        // to use Date for date/date-time, or branded types for uuid/email/uri
        if let Some(format) = &s.format {
            match format.as_str() {
                "date" | "date-time" | "uuid" | "email" | "uri" | "url" | "binary" | "byte" => {
                    return "string".to_string();
                }
                _ => {}
            }
        }
        "string".to_string()
    }

    /// Converts an array schema to TypeScript type.
    fn array_schema_to_ts_type(&self, arr: &ArraySchema) -> CodegenResult<String> {
        let item_type = self.schema_to_ts_type(&arr.items)?;
        Ok(format!("{item_type}[]"))
    }

    /// Generates an inline object type.
    fn generate_inline_object(&self, obj: &ObjectSchema) -> CodegenResult<String> {
        let mut parts = Vec::new();

        for (prop_name, prop_schema) in &obj.properties {
            let ts_name = prop_name.to_lower_camel_case();
            let ts_type = self.schema_to_ts_type(prop_schema)?;
            let optional = if obj.required.contains(prop_name) {
                ""
            } else {
                "?"
            };
            parts.push(format!("{ts_name}{optional}: {ts_type}"));
        }

        Ok(format!("{{ {} }}", parts.join("; ")))
    }
}

/// Formats a description as a JSDoc comment.
pub fn format_jsdoc(description: &str, indent_level: usize) -> String {
    let indent = "  ".repeat(indent_level);
    let lines: Vec<&str> = description.lines().collect();

    if lines.len() == 1 {
        format!("{indent}/** {} */\n", lines[0])
    } else {
        let mut output = format!("{indent}/**\n");
        for line in lines {
            let _ = writeln!(output, "{indent} * {line}");
        }
        let _ = writeln!(output, "{indent} */");
        output
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use themis_core::schema::{EnumValue, StringSchema};

    #[test]
    fn test_string_schema_to_ts_type() {
        let config = GeneratorConfig::default();
        let gen = TypeScriptTypeGenerator::new(&config);

        let schema = StringSchema::default();
        assert_eq!(gen.string_schema_to_ts_type(&schema), "string");
    }

    #[test]
    fn test_datetime_format_to_ts_type() {
        let config = GeneratorConfig::default();
        let gen = TypeScriptTypeGenerator::new(&config);

        let schema = StringSchema {
            format: Some("date-time".to_string()),
            ..Default::default()
        };
        assert_eq!(gen.string_schema_to_ts_type(&schema), "string");
    }

    #[test]
    fn test_array_schema_to_ts_type() {
        let config = GeneratorConfig::default();
        let gen = TypeScriptTypeGenerator::new(&config);

        let arr = ArraySchema {
            description: None,
            items: Box::new(Schema::String(StringSchema::default())),
            min_items: None,
            max_items: None,
            unique_items: false,
            nullable: false,
        };
        assert_eq!(gen.array_schema_to_ts_type(&arr).unwrap(), "string[]");
    }

    #[test]
    fn test_ref_schema_to_ts_type() {
        let config = GeneratorConfig::default();
        let gen = TypeScriptTypeGenerator::new(&config);

        let schema = Schema::Ref(themis_core::schema::RefSchema {
            reference: "#/components/schemas/User".to_string(),
        });
        assert_eq!(gen.schema_to_ts_type(&schema).unwrap(), "User");
    }

    #[test]
    fn test_generate_enum() {
        let config = GeneratorConfig::default();
        let gen = TypeScriptTypeGenerator::new(&config);

        let enum_schema = EnumSchema {
            description: None,
            values: vec![
                EnumValue {
                    value: serde_json::Value::String("ACTIVE".to_string()),
                    description: None,
                },
                EnumValue {
                    value: serde_json::Value::String("INACTIVE".to_string()),
                    description: None,
                },
            ],
            nullable: false,
        };

        let result = gen.generate_enum("Status", &enum_schema);
        assert!(result.contains("export type Status = \"ACTIVE\" | \"INACTIVE\";"));
    }

    #[test]
    fn test_format_jsdoc_single_line() {
        let result = format_jsdoc("A simple description", 0);
        assert_eq!(result, "/** A simple description */\n");
    }

    #[test]
    fn test_format_jsdoc_multi_line() {
        let result = format_jsdoc("Line 1\nLine 2", 0);
        assert!(result.contains("/**\n"));
        assert!(result.contains(" * Line 1\n"));
        assert!(result.contains(" * Line 2\n"));
        assert!(result.contains(" */\n"));
    }

    #[test]
    fn test_format_jsdoc_with_indent() {
        let result = format_jsdoc("Description", 1);
        assert!(result.starts_with("  /**"));
    }

    #[test]
    fn test_generate_simple_interface() {
        let config = GeneratorConfig {
            include_docs: false,
            ..Default::default()
        };
        let gen = TypeScriptTypeGenerator::new(&config);

        let obj = ObjectSchema {
            description: None,
            properties: {
                let mut props = HashMap::new();
                props.insert("id".to_string(), Schema::String(StringSchema::default()));
                props.insert("name".to_string(), Schema::String(StringSchema::default()));
                props
            },
            required: vec!["id".to_string()],
            additional_properties: None,
            nullable: false,
        };

        let result = gen.generate_interface("User", &obj).unwrap();
        assert!(result.contains("export interface User {"));
        assert!(result.contains("id: string;"));
        assert!(result.contains("name?: string;"));
    }
}
