//! Rust type generation from schemas.

use crate::config::GeneratorConfig;
use crate::error::CodegenResult;
use heck::ToUpperCamelCase;
use indexmap::IndexMap;
use std::collections::HashMap;
use std::fmt::Write;
use themis_core::schema::{
    AllOfSchema, AnyOfSchema, EnumSchema, ObjectSchema, OneOfSchema, Schema,
};

/// Generates Rust type definitions from schemas.
pub struct RustTypeGenerator<'a> {
    config: &'a GeneratorConfig,
    /// Maps schema names to their generated Rust type names
    type_map: HashMap<String, String>,
}

impl<'a> RustTypeGenerator<'a> {
    /// Creates a new type generator.
    pub fn new(config: &'a GeneratorConfig) -> Self {
        Self {
            config,
            type_map: HashMap::new(),
        }
    }

    /// Generates Rust structs from a map of named schemas.
    pub fn generate_types(&mut self, schemas: &IndexMap<String, Schema>) -> CodegenResult<String> {
        let mut output = String::new();

        // Generate header comment
        output.push_str("// Auto-generated by themis-codegen. DO NOT EDIT.\n\n");

        // Generate imports
        output.push_str("use serde::{Deserialize, Serialize};\n");
        if self.config.include_validation {
            output.push_str("use validator::Validate;\n");
        }
        output.push('\n');

        // First pass: register all type names
        for name in schemas.keys() {
            let rust_name = self.schema_name_to_rust_type(name);
            self.type_map.insert(name.clone(), rust_name);
        }

        // Second pass: generate types
        for (name, schema) in schemas {
            let type_code = self.generate_schema_type(name, schema)?;
            output.push_str(&type_code);
            output.push('\n');
        }

        Ok(output)
    }

    /// Generates a Rust type for a named schema.
    fn generate_schema_type(&self, name: &str, schema: &Schema) -> CodegenResult<String> {
        let rust_name = self.schema_name_to_rust_type(name);

        match schema {
            Schema::Object(obj) => self.generate_struct(&rust_name, obj),
            Schema::Enum(enum_schema) => Ok(self.generate_enum(&rust_name, enum_schema)),
            Schema::OneOf(one_of) => self.generate_one_of_enum(&rust_name, one_of),
            Schema::AllOf(all_of) => self.generate_all_of_struct(&rust_name, all_of),
            Schema::AnyOf(any_of) => self.generate_any_of_enum(&rust_name, any_of),
            _ => {
                // For simple types, generate a type alias
                let inner_type = self.schema_to_rust_type(schema)?;
                Ok(format!("pub type {rust_name} = {inner_type};\n"))
            }
        }
    }

    /// Generates a Rust struct from an object schema.
    fn generate_struct(&self, name: &str, obj: &ObjectSchema) -> CodegenResult<String> {
        let mut output = String::new();

        // Doc comment
        if let Some(desc) = &obj.description {
            if self.config.include_docs {
                output.push_str(&format_doc_comment(desc, 0));
            }
        }

        // Derive macros
        let mut derives = vec!["Debug", "Clone"];
        if self.config.include_serialization {
            derives.extend(["Serialize", "Deserialize"]);
        }
        if self.config.include_validation {
            derives.push("Validate");
        }

        let _ = writeln!(output, "#[derive({})]", derives.join(", "));

        if self.config.include_serialization {
            output.push_str("#[serde(rename_all = \"camelCase\")]\n");
        }

        // Struct definition
        let _ = writeln!(output, "pub struct {name} {{");

        // Sort properties for stable output
        let mut props: Vec<_> = obj.properties.iter().collect();
        props.sort_by(|a, b| a.0.cmp(b.0));

        for (prop_name, prop_schema) in props {
            let is_required = obj.required.contains(prop_name);
            let field_code = self.generate_field(prop_name, prop_schema, is_required)?;
            output.push_str(&field_code);
        }

        output.push_str("}\n");

        Ok(output)
    }

    /// Generates a Rust struct field.
    fn generate_field(&self, name: &str, schema: &Schema, required: bool) -> CodegenResult<String> {
        let mut output = String::new();

        // Get field description
        if self.config.include_docs {
            if let Some(desc) = Self::get_schema_description(schema) {
                output.push_str(&format_doc_comment(&desc, 1));
            }
        }

        let rust_name = self.config.field_naming.convert(name);
        let rust_type = self.schema_to_rust_type(schema)?;
        let is_nullable = Self::is_schema_nullable(schema);

        // Determine if we need Option
        let needs_option = !required || is_nullable;
        let final_type = if needs_option {
            format!("Option<{rust_type}>")
        } else {
            rust_type
        };

        // Add validation attributes
        if self.config.include_validation {
            let validation_attrs = Self::generate_validation_attributes(schema);
            if !validation_attrs.is_empty() {
                let _ = writeln!(output, "    #[validate({validation_attrs})]");
            }
        }

        // Add serde attributes if field name differs
        if self.config.include_serialization && rust_name != name {
            let _ = writeln!(output, "    #[serde(rename = \"{name}\")]");
        }

        // Add skip_serializing_if for optional fields
        if self.config.include_serialization && needs_option {
            output.push_str("    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n");
        }

        let _ = writeln!(output, "    pub {rust_name}: {final_type},");

        Ok(output)
    }

    /// Generates a Rust enum from an enum schema.
    fn generate_enum(&self, name: &str, schema: &EnumSchema) -> String {
        let mut output = String::new();

        // Doc comment
        if let Some(desc) = &schema.description {
            if self.config.include_docs {
                output.push_str(&format_doc_comment(desc, 0));
            }
        }

        // Derive macros

        let mut derives = vec!["Debug", "Clone", "Copy", "PartialEq", "Eq"];
        if self.config.include_serialization {
            derives.extend(["Serialize", "Deserialize"]);
        }
        let _ = writeln!(output, "#[derive({})]", derives.join(", "));

        if self.config.include_serialization {
            output.push_str("#[serde(rename_all = \"SCREAMING_SNAKE_CASE\")]\n");
        }

        // Enum definition
        let _ = writeln!(output, "pub enum {name} {{");

        for value in &schema.values {
            let variant_name = Self::enum_value_to_variant(&value.value);

            // Doc comment for variant
            if let Some(desc) = &value.description {
                if self.config.include_docs {
                    output.push_str(&format_doc_comment(desc, 1));
                }
            }

            let _ = writeln!(output, "    {variant_name},");
        }

        output.push_str("}\n");

        output
    }

    /// Generates a Rust enum from a oneOf schema.
    fn generate_one_of_enum(&self, name: &str, schema: &OneOfSchema) -> CodegenResult<String> {
        let mut output = String::new();

        // Doc comment
        if let Some(desc) = &schema.description {
            if self.config.include_docs {
                output.push_str(&format_doc_comment(desc, 0));
            }
        }

        // Derive macros

        let mut derives = vec!["Debug", "Clone"];
        if self.config.include_serialization {
            derives.extend(["Serialize", "Deserialize"]);
        }
        let _ = writeln!(output, "#[derive({})]", derives.join(", "));

        if self.config.include_serialization {
            output.push_str("#[serde(untagged)]\n");
        }

        // Enum definition
        let _ = writeln!(output, "pub enum {name} {{");

        for (i, variant_schema) in schema.schemas.iter().enumerate() {
            let variant_name = Self::infer_variant_name(variant_schema, i);
            let variant_type = self.schema_to_rust_type(variant_schema)?;
            let _ = writeln!(output, "    {variant_name}({variant_type}),");
        }

        output.push_str("}\n");

        Ok(output)
    }

    /// Generates a flattened struct from an allOf schema.
    fn generate_all_of_struct(&self, name: &str, schema: &AllOfSchema) -> CodegenResult<String> {
        let mut output = String::new();

        // Doc comment
        if let Some(desc) = &schema.description {
            if self.config.include_docs {
                output.push_str(&format_doc_comment(desc, 0));
            }
        }

        // Derive macros

        let mut derives = vec!["Debug", "Clone"];
        if self.config.include_serialization {
            derives.extend(["Serialize", "Deserialize"]);
        }
        let _ = writeln!(output, "#[derive({})]", derives.join(", "));

        // Struct definition
        let _ = writeln!(output, "pub struct {name} {{");

        // For allOf, we flatten all object properties into one struct
        for (i, sub_schema) in schema.schemas.iter().enumerate() {
            match sub_schema {
                Schema::Object(obj) => {
                    // Inline the properties
                    let mut props: Vec<_> = obj.properties.iter().collect();
                    props.sort_by(|a, b| a.0.cmp(b.0));

                    for (prop_name, prop_schema) in props {
                        let is_required = obj.required.contains(prop_name);
                        let field_code =
                            self.generate_field(prop_name, prop_schema, is_required)?;
                        output.push_str(&field_code);
                    }
                }
                Schema::Ref(_) => {
                    // For refs, we use #[serde(flatten)]
                    let rust_type = self.schema_to_rust_type(sub_schema)?;
                    output.push_str("    #[serde(flatten)]\n");
                    let _ = writeln!(output, "    pub base{i}: {rust_type},");
                }
                _ => {
                    // Skip non-object schemas in allOf
                }
            }
        }

        output.push_str("}\n");

        Ok(output)
    }

    /// Generates an enum from an anyOf schema.
    fn generate_any_of_enum(&self, name: &str, schema: &AnyOfSchema) -> CodegenResult<String> {
        // AnyOf is similar to oneOf in code generation
        let one_of = OneOfSchema {
            description: schema.description.clone(),
            schemas: schema.schemas.clone(),
            discriminator: None,
        };
        self.generate_one_of_enum(name, &one_of)
    }

    /// Converts a schema to a Rust type string.
    pub fn schema_to_rust_type(&self, schema: &Schema) -> CodegenResult<String> {
        match schema {
            Schema::String(s) => Ok(Self::string_format_to_rust_type(s.format.as_deref())),
            Schema::Integer(i) => Ok(Self::integer_format_to_rust_type(i.format.as_deref())),
            Schema::Number(n) => Ok(Self::number_format_to_rust_type(n.format.as_deref())),
            Schema::Boolean(_) => Ok("bool".to_string()),
            Schema::Array(arr) => {
                let inner = self.schema_to_rust_type(&arr.items)?;
                Ok(format!("Vec<{inner}>"))
            }
            Schema::Object(_) => Ok("serde_json::Value".to_string()),
            Schema::Ref(r) => Ok(self.resolve_ref_to_rust_type(&r.reference)),
            Schema::OneOf(_) | Schema::AllOf(_) | Schema::AnyOf(_) => {
                Ok("serde_json::Value".to_string())
            }
            Schema::Enum(_) => Ok("String".to_string()), // Inline enums as String
            Schema::Null => Ok("()".to_string()),
        }
    }

    /// Converts a string format to a Rust type.
    fn string_format_to_rust_type(format: Option<&str>) -> String {
        match format {
            Some("uuid") => "uuid::Uuid".to_string(),
            Some("date-time") => "chrono::DateTime<chrono::Utc>".to_string(),
            Some("date") => "chrono::NaiveDate".to_string(),
            Some("time") => "chrono::NaiveTime".to_string(),
            Some("byte" | "binary") => "Vec<u8>".to_string(),
            // email, uri, hostname, ipv4, ipv6 and others fall through to String
            _ => "String".to_string(),
        }
    }

    /// Converts an integer format to a Rust type.
    fn integer_format_to_rust_type(format: Option<&str>) -> String {
        match format {
            Some("int32") => "i32".to_string(),
            Some("uint32") => "u32".to_string(),
            Some("uint64") => "u64".to_string(),
            _ => "i64".to_string(), // Default to i64
        }
    }

    /// Converts a number format to a Rust type.
    fn number_format_to_rust_type(format: Option<&str>) -> String {
        match format {
            Some("float") => "f32".to_string(),
            _ => "f64".to_string(), // Default to f64
        }
    }

    /// Resolves a $ref to a Rust type name.
    fn resolve_ref_to_rust_type(&self, reference: &str) -> String {
        // References are typically like "#/components/schemas/User"
        let name = reference.rsplit('/').next().unwrap_or(reference);

        // Check if we have a registered type name
        self.type_map
            .get(name)
            .map_or_else(|| self.schema_name_to_rust_type(name), Clone::clone)
    }

    /// Converts a schema name to a Rust type name.
    fn schema_name_to_rust_type(&self, name: &str) -> String {
        let mut type_name = name.to_upper_camel_case();

        if let Some(prefix) = &self.config.type_prefix {
            type_name = format!("{prefix}{type_name}");
        }

        if let Some(suffix) = &self.config.type_suffix {
            type_name = format!("{type_name}{suffix}");
        }

        type_name
    }

    /// Converts an enum value to a Rust variant name.
    fn enum_value_to_variant(value: &serde_json::Value) -> String {
        match value {
            serde_json::Value::String(s) => s.to_upper_camel_case(),
            serde_json::Value::Number(n) => format!("V{n}"),
            _ => "Unknown".to_string(),
        }
    }

    /// Infers a variant name for a oneOf/anyOf schema.
    fn infer_variant_name(schema: &Schema, index: usize) -> String {
        match schema {
            Schema::Ref(r) => {
                let name = r.reference.rsplit('/').next().unwrap_or("Unknown");
                name.to_upper_camel_case()
            }
            Schema::String(_) => "String".to_string(),
            Schema::Integer(_) => "Integer".to_string(),
            Schema::Number(_) => "Number".to_string(),
            Schema::Boolean(_) => "Boolean".to_string(),
            Schema::Array(_) => "Array".to_string(),
            Schema::Object(_) => format!("Object{index}"),
            _ => format!("Variant{index}"),
        }
    }

    /// Gets the description from a schema.
    fn get_schema_description(schema: &Schema) -> Option<String> {
        match schema {
            Schema::String(s) => s.description.clone(),
            Schema::Integer(i) => i.description.clone(),
            Schema::Number(n) => n.description.clone(),
            Schema::Boolean(b) => b.description.clone(),
            Schema::Array(a) => a.description.clone(),
            Schema::Object(o) => o.description.clone(),
            Schema::Enum(e) => e.description.clone(),
            Schema::OneOf(o) => o.description.clone(),
            Schema::AllOf(a) => a.description.clone(),
            Schema::AnyOf(a) => a.description.clone(),
            Schema::Ref(_) | Schema::Null => None,
        }
    }

    /// Checks if a schema is nullable.
    const fn is_schema_nullable(schema: &Schema) -> bool {
        match schema {
            Schema::String(s) => s.nullable,
            Schema::Integer(i) => i.nullable,
            Schema::Number(n) => n.nullable,
            Schema::Boolean(b) => b.nullable,
            Schema::Array(a) => a.nullable,
            Schema::Object(o) => o.nullable,
            Schema::Enum(e) => e.nullable,
            Schema::Ref(_)
            | Schema::OneOf(_)
            | Schema::AllOf(_)
            | Schema::AnyOf(_)
            | Schema::Null => false,
        }
    }

    /// Generates validation attributes for a schema.
    ///
    /// Maps OpenAPI schema constraints to validator crate attributes:
    /// - minLength/maxLength → length(min, max)
    /// - minimum/maximum → range(min, max)
    /// - pattern → regex
    /// - format: email → email
    /// - format: url → url
    /// - minItems/maxItems → length(min, max)
    fn generate_validation_attributes(schema: &Schema) -> String {
        let mut attrs = Vec::new();

        match schema {
            Schema::String(s) => {
                // Length constraints
                match (s.min_length, s.max_length) {
                    (Some(min), Some(max)) => {
                        attrs.push(format!("length(min = {min}, max = {max})"));
                    }
                    (Some(min), None) => {
                        attrs.push(format!("length(min = {min})"));
                    }
                    (None, Some(max)) => {
                        attrs.push(format!("length(max = {max})"));
                    }
                    (None, None) => {}
                }

                // Pattern constraint
                if let Some(pattern) = &s.pattern {
                    // Escape the pattern for use in a string literal
                    let escaped = pattern.replace('\\', "\\\\").replace('"', "\\\"");
                    attrs.push(format!("regex(path = \"*{escaped}*\")"));
                }

                // Format-based validation
                if let Some(format) = &s.format {
                    match format.as_str() {
                        "email" => attrs.push("email".to_string()),
                        "uri" | "url" => attrs.push("url".to_string()),
                        _ => {}
                    }
                }
            }
            Schema::Integer(i) => {
                // Range constraints
                match (i.minimum, i.maximum) {
                    (Some(min), Some(max)) => {
                        attrs.push(format!("range(min = {min}, max = {max})"));
                    }
                    (Some(min), None) => {
                        attrs.push(format!("range(min = {min})"));
                    }
                    (None, Some(max)) => {
                        attrs.push(format!("range(max = {max})"));
                    }
                    (None, None) => {}
                }
            }
            Schema::Number(n) => {
                // Range constraints for floats
                match (n.minimum, n.maximum) {
                    (Some(min), Some(max)) => {
                        attrs.push(format!("range(min = {min}, max = {max})"));
                    }
                    (Some(min), None) => {
                        attrs.push(format!("range(min = {min})"));
                    }
                    (None, Some(max)) => {
                        attrs.push(format!("range(max = {max})"));
                    }
                    (None, None) => {}
                }
            }
            Schema::Array(a) => {
                // Length constraints for arrays
                match (a.min_items, a.max_items) {
                    (Some(min), Some(max)) => {
                        attrs.push(format!("length(min = {min}, max = {max})"));
                    }
                    (Some(min), None) => {
                        attrs.push(format!("length(min = {min})"));
                    }
                    (None, Some(max)) => {
                        attrs.push(format!("length(max = {max})"));
                    }
                    (None, None) => {}
                }
            }
            // Other schema types don't have simple validation constraints
            _ => {}
        }

        attrs.join(", ")
    }
}

/// Formats a doc comment.
fn format_doc_comment(text: &str, indent: usize) -> String {
    let indent_str = "    ".repeat(indent);
    let lines: Vec<&str> = text.lines().collect();

    if lines.len() == 1 {
        format!("{indent_str}/// {}\n", lines[0].trim())
    } else {
        let mut output = String::new();
        for line in lines {
            if line.trim().is_empty() {
                let _ = writeln!(output, "{indent_str}///");
            } else {
                let _ = writeln!(output, "{indent_str}/// {}", line.trim());
            }
        }
        output
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use themis_core::schema::{ArraySchema, EnumValue, RefSchema, StringSchema};

    fn make_config() -> GeneratorConfig {
        GeneratorConfig::default()
    }

    #[test]
    fn test_string_schema_to_rust_type() {
        let config = make_config();
        let gen = RustTypeGenerator::new(&config);

        let schema = Schema::String(StringSchema::default());
        assert_eq!(gen.schema_to_rust_type(&schema).unwrap(), "String");
    }

    #[test]
    fn test_uuid_format_to_rust_type() {
        let config = make_config();
        let gen = RustTypeGenerator::new(&config);

        let schema = Schema::String(StringSchema {
            format: Some("uuid".to_string()),
            ..Default::default()
        });
        assert_eq!(gen.schema_to_rust_type(&schema).unwrap(), "uuid::Uuid");
    }

    #[test]
    fn test_datetime_format_to_rust_type() {
        let config = make_config();
        let gen = RustTypeGenerator::new(&config);

        let schema = Schema::String(StringSchema {
            format: Some("date-time".to_string()),
            ..Default::default()
        });
        assert_eq!(
            gen.schema_to_rust_type(&schema).unwrap(),
            "chrono::DateTime<chrono::Utc>"
        );
    }

    #[test]
    fn test_array_schema_to_rust_type() {
        let config = make_config();
        let gen = RustTypeGenerator::new(&config);

        let schema = Schema::Array(ArraySchema {
            items: Box::new(Schema::String(StringSchema::default())),
            ..Default::default()
        });
        assert_eq!(gen.schema_to_rust_type(&schema).unwrap(), "Vec<String>");
    }

    #[test]
    fn test_ref_schema_to_rust_type() {
        let config = make_config();
        let gen = RustTypeGenerator::new(&config);

        let schema = Schema::Ref(RefSchema {
            reference: "#/components/schemas/User".to_string(),
        });
        assert_eq!(gen.schema_to_rust_type(&schema).unwrap(), "User");
    }

    #[test]
    fn test_generate_simple_struct() {
        let config = make_config();
        let gen = RustTypeGenerator::new(&config);

        let obj = ObjectSchema {
            description: Some("A user object".to_string()),
            properties: {
                let mut props = IndexMap::new();
                props.insert(
                    "id".to_string(),
                    Schema::String(StringSchema {
                        format: Some("uuid".to_string()),
                        ..Default::default()
                    }),
                );
                props.insert("name".to_string(), Schema::String(StringSchema::default()));
                props
            },
            required: vec!["id".to_string()],
            ..Default::default()
        };

        let code = gen.generate_struct("User", &obj).unwrap();
        assert!(code.contains("pub struct User"));
        assert!(code.contains("pub id: uuid::Uuid"));
        assert!(code.contains("pub name: Option<String>"));
        assert!(code.contains("/// A user object"));
    }

    #[test]
    fn test_generate_enum() {
        let config = make_config();
        let gen = RustTypeGenerator::new(&config);

        let schema = EnumSchema {
            description: Some("User status".to_string()),
            values: vec![
                EnumValue {
                    value: serde_json::Value::String("active".to_string()),
                    description: Some("User is active".to_string()),
                },
                EnumValue {
                    value: serde_json::Value::String("inactive".to_string()),
                    description: None,
                },
            ],
            nullable: false,
        };

        let code = gen.generate_enum("UserStatus", &schema);
        assert!(code.contains("pub enum UserStatus"));
        assert!(code.contains("Active"));
        assert!(code.contains("Inactive"));
    }

    #[test]
    fn test_format_doc_comment_single_line() {
        let result = format_doc_comment("A simple description", 0);
        assert_eq!(result, "/// A simple description\n");
    }

    #[test]
    fn test_format_doc_comment_multi_line() {
        let result = format_doc_comment("Line 1\nLine 2", 0);
        assert!(result.contains("/// Line 1\n"));
        assert!(result.contains("/// Line 2\n"));
    }

    #[test]
    fn test_format_doc_comment_with_indent() {
        let result = format_doc_comment("A description", 1);
        assert_eq!(result, "    /// A description\n");
    }

    #[test]
    fn test_validation_attributes_string_length() {
        use themis_core::schema::StringSchema;
        let schema = Schema::String(StringSchema {
            min_length: Some(1),
            max_length: Some(100),
            ..Default::default()
        });

        let attrs = RustTypeGenerator::generate_validation_attributes(&schema);
        assert_eq!(attrs, "length(min = 1, max = 100)");
    }

    #[test]
    fn test_validation_attributes_email() {
        use themis_core::schema::StringSchema;
        let schema = Schema::String(StringSchema {
            format: Some("email".to_string()),
            ..Default::default()
        });

        let attrs = RustTypeGenerator::generate_validation_attributes(&schema);
        assert_eq!(attrs, "email");
    }

    #[test]
    fn test_validation_attributes_url() {
        use themis_core::schema::StringSchema;
        let schema = Schema::String(StringSchema {
            format: Some("uri".to_string()),
            ..Default::default()
        });

        let attrs = RustTypeGenerator::generate_validation_attributes(&schema);
        assert_eq!(attrs, "url");
    }

    #[test]
    fn test_validation_attributes_integer_range() {
        use themis_core::schema::IntegerSchema;
        let schema = Schema::Integer(IntegerSchema {
            minimum: Some(0),
            maximum: Some(100),
            ..Default::default()
        });

        let attrs = RustTypeGenerator::generate_validation_attributes(&schema);
        assert_eq!(attrs, "range(min = 0, max = 100)");
    }

    #[test]
    fn test_validation_attributes_array_length() {
        let schema = Schema::Array(ArraySchema {
            items: Box::new(Schema::String(StringSchema::default())),
            min_items: Some(1),
            max_items: Some(10),
            ..Default::default()
        });

        let attrs = RustTypeGenerator::generate_validation_attributes(&schema);
        assert_eq!(attrs, "length(min = 1, max = 10)");
    }

    #[test]
    fn test_validation_derive_in_struct() {
        let config = make_config();
        let gen = RustTypeGenerator::new(&config);

        let obj = ObjectSchema {
            properties: {
                let mut props = IndexMap::new();
                props.insert("name".to_string(), Schema::String(StringSchema::default()));
                props
            },
            required: vec!["name".to_string()],
            ..Default::default()
        };

        let code = gen.generate_struct("User", &obj).unwrap();
        assert!(code.contains("Validate"));
        assert!(code.contains("#[derive("));
    }
}
