//! Python code generator.

// Allow some pedantic clippy lints that are acceptable in generated code
#![allow(clippy::missing_const_for_fn)]
#![allow(clippy::for_kv_map)]
#![allow(clippy::unused_self)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::manual_map)]

use crate::config::GeneratorConfig;
use crate::error::{CodegenError, CodegenResult};
use crate::python::types::{format_docstring, PythonTypeGenerator};
use crate::traits::{CodeGenerator, GeneratedCode, GeneratedFile};
use heck::{ToSnakeCase, ToUpperCamelCase};
use std::fmt::Write;
use themis_core::operation::ParameterLocation;
use themis_core::{Contract, Operation};

/// Python code generator.
///
/// Generates Python dataclasses, httpx clients, and FastAPI handler signatures
/// from Themis contracts.
pub struct PythonGenerator {
    config: GeneratorConfig,
}

impl PythonGenerator {
    /// Creates a new Python generator with the given configuration.
    pub fn new(config: GeneratorConfig) -> Self {
        Self { config }
    }

    /// Generates the types file (dataclasses).
    fn generate_types_file(&self, contract: &Contract) -> CodegenResult<String> {
        let mut type_gen = PythonTypeGenerator::new(&self.config);

        let mut output = String::new();

        // Header
        output.push_str("# Auto-generated by themis-codegen. DO NOT EDIT.\n");
        let _ = writeln!(
            output,
            "# Contract: {} v{}\n",
            contract.metadata.service_name, contract.version
        );

        // Generate schema types
        let types = type_gen.generate_types(&contract.schemas)?;
        output.push_str(&types);

        // Generate request/response types for operations
        output.push_str("\n# Request/Response types\n\n");
        for (_, op) in &contract.operations {
            output.push_str(&self.generate_request_type(op, &type_gen)?);
            output.push_str("\n\n");
            output.push_str(&self.generate_response_type(op, &type_gen)?);
            output.push_str("\n\n");
        }

        // Generate error types
        output.push_str("# Error types\n\n");
        output.push_str(&self.generate_error_types(contract)?);

        Ok(output)
    }

    /// Generates a request dataclass for an operation.
    fn generate_request_type(
        &self,
        op: &Operation,
        type_gen: &PythonTypeGenerator,
    ) -> CodegenResult<String> {
        let mut output = String::new();
        let type_name = format!("{}Request", op.operation_id.to_upper_camel_case());

        output.push_str("@dataclass\n");
        let _ = writeln!(output, "class {type_name}:");

        if self.config.include_docs {
            if let Some(desc) = &op.description {
                output.push_str(&format_docstring(
                    &format!("Request for {}.\n\n{}", op.operation_id, desc),
                    1,
                ));
            } else {
                output.push_str(&format_docstring(
                    &format!("Request for {}.", op.operation_id),
                    1,
                ));
            }
        }

        // Collect required and optional fields
        let mut required_fields: Vec<(String, String, Option<String>)> = Vec::new();
        let mut optional_fields: Vec<(String, String, Option<String>)> = Vec::new();

        // Path parameters (always required)
        for param in &op.parameters {
            if param.location == ParameterLocation::Path {
                let py_name = param.name.to_snake_case();
                let py_type = type_gen.schema_to_py_type(&param.schema)?;
                required_fields.push((py_name, py_type, param.description.clone()));
            }
        }

        // Query parameters
        for param in &op.parameters {
            if param.location == ParameterLocation::Query {
                let py_name = param.name.to_snake_case();
                let py_type = type_gen.schema_to_py_type(&param.schema)?;
                if param.required {
                    required_fields.push((py_name, py_type, param.description.clone()));
                } else {
                    optional_fields.push((py_name, py_type, param.description.clone()));
                }
            }
        }

        // Request body (if present, add as required field)
        if let Some(body) = &op.request_body {
            if let Some(media_type) = body.content.get("application/json") {
                let py_type = type_gen.schema_to_py_type(&media_type.schema)?;
                if body.required {
                    required_fields.push(("body".to_string(), py_type, None));
                } else {
                    optional_fields.push(("body".to_string(), py_type, None));
                }
            }
        }

        // Write required fields first
        for (name, py_type, desc) in &required_fields {
            if self.config.include_docs {
                if let Some(d) = desc {
                    let _ = writeln!(output, "    # {d}");
                }
            }
            let _ = writeln!(output, "    {name}: {py_type}");
        }

        // Write optional fields with defaults
        for (name, py_type, desc) in &optional_fields {
            if self.config.include_docs {
                if let Some(d) = desc {
                    let _ = writeln!(output, "    # {d}");
                }
            }
            let _ = writeln!(output, "    {name}: Optional[{py_type}] = None");
        }

        // If no fields, add pass
        if required_fields.is_empty() && optional_fields.is_empty() {
            output.push_str("    pass\n");
        }

        Ok(output)
    }

    /// Generates a response type for an operation.
    fn generate_response_type(
        &self,
        op: &Operation,
        type_gen: &PythonTypeGenerator,
    ) -> CodegenResult<String> {
        let mut output = String::new();
        let type_name = format!("{}Response", op.operation_id.to_upper_camel_case());

        // Find success responses and get their schemas
        let success_schemas: Vec<_> = op
            .responses
            .iter()
            .filter(|(code, _)| code.starts_with('2'))
            .filter_map(|(_, response)| {
                response
                    .content
                    .get("application/json")
                    .map(|media| &media.schema)
            })
            .collect();

        if success_schemas.len() == 1 {
            let py_type = type_gen.schema_to_py_type(success_schemas[0])?;
            if self.config.include_docs {
                let _ = writeln!(output, "# Response from {}.", op.operation_id);
            }
            let _ = writeln!(output, "{type_name} = {py_type}");
        } else if success_schemas.is_empty() {
            // No response body (e.g., 204)
            if self.config.include_docs {
                let _ = writeln!(output, "# Response from {} (no body).", op.operation_id);
            }
            let _ = writeln!(output, "{type_name} = None");
        } else {
            // Multiple success responses - create a Union
            let variants: Vec<String> = success_schemas
                .iter()
                .filter_map(|schema| type_gen.schema_to_py_type(schema).ok())
                .collect();
            if self.config.include_docs {
                let _ = writeln!(output, "# Response from {}.", op.operation_id);
            }
            let _ = writeln!(output, "{type_name} = Union[{}]", variants.join(", "));
        }

        Ok(output)
    }

    /// Generates error types for the service.
    fn generate_error_types(&self, contract: &Contract) -> CodegenResult<String> {
        let mut output = String::new();
        let service_name = contract.metadata.service_name.to_upper_camel_case();

        // Generate base error dataclass
        output.push_str("@dataclass\n");
        let _ = writeln!(output, "class {service_name}Error:");
        output.push_str(&format_docstring("Base error class for service errors.", 1));
        output.push_str("    code: str\n");
        output.push_str("    message: str\n");
        output.push_str("    details: Optional[dict[str, Any]] = None\n");
        output.push_str("    request_id: Optional[str] = None\n");
        output.push_str("    timestamp: Optional[datetime] = None\n");
        output.push_str("\n\n");

        // Generate specific error types
        let error_types = [
            ("BadRequest", "400", "BAD_REQUEST", "Bad request error"),
            (
                "Unauthorized",
                "401",
                "UNAUTHENTICATED",
                "Unauthorized error",
            ),
            ("Forbidden", "403", "PERMISSION_DENIED", "Forbidden error"),
            ("NotFound", "404", "NOT_FOUND", "Not found error"),
            (
                "InternalError",
                "500",
                "INTERNAL_ERROR",
                "Internal server error",
            ),
        ];

        for (name, _status, code, desc) in error_types {
            output.push_str("@dataclass\n");
            let _ = writeln!(
                output,
                "class {service_name}{name}Error({service_name}Error):"
            );
            output.push_str(&format_docstring(desc, 1));
            let _ = writeln!(output, "    code: str = \"{code}\"");
            output.push_str("\n\n");
        }

        // Generate Union of all errors
        let error_names: Vec<String> = error_types
            .iter()
            .map(|(name, _, _, _)| format!("{service_name}{name}Error"))
            .collect();
        let _ = writeln!(
            output,
            "{service_name}ServiceError = Union[{}]",
            error_names.join(", ")
        );
        output.push('\n');

        Ok(output)
    }

    /// Generates the httpx client file.
    fn generate_client_file(&self, contract: &Contract) -> CodegenResult<String> {
        let mut output = String::new();
        let service_name = contract.metadata.service_name.to_upper_camel_case();
        let service_snake = contract.metadata.service_name.to_snake_case();

        // Header
        output.push_str("# Auto-generated by themis-codegen. DO NOT EDIT.\n");
        let _ = writeln!(
            output,
            "# Contract: {} v{}\n",
            contract.metadata.service_name, contract.version
        );

        // Imports
        output.push_str("from __future__ import annotations\n\n");
        output.push_str("from dataclasses import asdict\n");
        output.push_str("from typing import Any, Optional, Union\n\n");
        output.push_str("import httpx\n\n");

        // Import types from types module
        let _ = writeln!(output, "from .types import (");
        for (_, op) in &contract.operations {
            let request_type = format!("{}Request", op.operation_id.to_upper_camel_case());
            let response_type = format!("{}Response", op.operation_id.to_upper_camel_case());
            let _ = writeln!(output, "    {request_type},");
            let _ = writeln!(output, "    {response_type},");
        }
        let _ = writeln!(output, "    {service_name}ServiceError,");
        output.push_str(")\n\n");

        // Result type
        let _ = writeln!(output, "# Result type for API calls");
        let _ = writeln!(output, "class {service_name}Result:");
        output.push_str(&format_docstring("Result wrapper for API calls.", 1));
        output.push_str("    def __init__(\n");
        output.push_str("        self,\n");
        output.push_str("        ok: bool,\n");
        output.push_str("        data: Any = None,\n");
        let _ = writeln!(
            output,
            "        error: Optional[{service_name}ServiceError] = None,"
        );
        output.push_str("    ) -> None:\n");
        output.push_str("        self.ok = ok\n");
        output.push_str("        self.data = data\n");
        output.push_str("        self.error = error\n");
        output.push_str("\n\n");

        // Client class
        let _ = writeln!(output, "class {service_name}Client:");
        output.push_str(&format_docstring(
            &format!("Client for {}.", contract.metadata.service_name),
            1,
        ));

        // __init__
        output.push_str("    def __init__(\n");
        output.push_str("        self,\n");
        output.push_str("        base_url: str,\n");
        output.push_str("        headers: Optional[dict[str, str]] = None,\n");
        output.push_str("        timeout: float = 30.0,\n");
        output.push_str("    ) -> None:\n");
        output.push_str("        self.base_url = base_url.rstrip(\"/\")\n");
        output.push_str("        self.headers = headers or {}\n");
        output.push_str("        self._client = httpx.Client(\n");
        output.push_str("            base_url=self.base_url,\n");
        output.push_str(
            "            headers={\"Content-Type\": \"application/json\", **self.headers},\n",
        );
        output.push_str("            timeout=timeout,\n");
        output.push_str("        )\n\n");

        // __enter__ and __exit__ for context manager
        output.push_str("    def __enter__(self) -> \"");
        let _ = writeln!(output, "{service_name}Client\":");
        output.push_str("        return self\n\n");

        output.push_str("    def __exit__(self, *args: Any) -> None:\n");
        output.push_str("        self._client.close()\n\n");

        // close method
        output.push_str("    def close(self) -> None:\n");
        output.push_str(&format_docstring("Close the HTTP client.", 2));
        output.push_str("        self._client.close()\n\n");

        // Private request method
        output.push_str("    def _request(\n");
        output.push_str("        self,\n");
        output.push_str("        method: str,\n");
        output.push_str("        path: str,\n");
        output.push_str("        json: Optional[dict[str, Any]] = None,\n");
        output.push_str("        params: Optional[dict[str, Any]] = None,\n");
        let _ = writeln!(output, "    ) -> {service_name}Result:");
        output.push_str("        try:\n");
        output.push_str("            response = self._client.request(\n");
        output.push_str("                method=method,\n");
        output.push_str("                url=path,\n");
        output.push_str("                json=json,\n");
        output.push_str("                params=params,\n");
        output.push_str("            )\n");
        output.push_str("            if response.is_success:\n");
        output.push_str("                if response.status_code == 204:\n");
        let _ = writeln!(
            output,
            "                    return {service_name}Result(ok=True, data=None)"
        );
        output.push_str("                data = response.json()\n");
        let _ = writeln!(
            output,
            "                return {service_name}Result(ok=True, data=data)"
        );
        output.push_str("            else:\n");
        output.push_str("                error_data = response.json()\n");
        let _ = writeln!(
            output,
            "                return {service_name}Result(ok=False, error=error_data)"
        );
        output.push_str("        except httpx.HTTPError as e:\n");
        let _ = writeln!(output, "            return {service_name}Result(");
        output.push_str("                ok=False,\n");
        output.push_str(
            "                error={\"code\": \"INTERNAL_ERROR\", \"message\": str(e)},\n",
        );
        output.push_str("            )\n\n");

        // Generate operation methods
        for (_, op) in &contract.operations {
            let method_name = op.operation_id.to_snake_case();
            let request_type = format!("{}Request", op.operation_id.to_upper_camel_case());
            // Note: response_type not used directly since we return Result wrapper
            let _response_type = format!("{}Response", op.operation_id.to_upper_camel_case());

            // Method signature
            output.push_str(&format!("    def {method_name}(\n"));
            output.push_str("        self,\n");
            let _ = writeln!(output, "        request: {request_type},");
            let _ = writeln!(output, "    ) -> {service_name}Result:");

            // Docstring
            if self.config.include_docs {
                if let Some(summary) = &op.summary {
                    output.push_str(&format_docstring(summary, 2));
                }
            }

            // Build path with parameter substitution
            let path = self.build_path_expression(op);
            let _ = writeln!(output, "        path = {path}");

            // Build query params if any
            let query_params: Vec<_> = op
                .parameters
                .iter()
                .filter(|p| p.location == ParameterLocation::Query)
                .collect();

            if query_params.is_empty() {
                output.push_str("        params = None\n");
            } else {
                output.push_str("        params = {}\n");
                for param in query_params {
                    let py_name = param.name.to_snake_case();
                    if param.required {
                        let _ = writeln!(
                            output,
                            "        params[\"{}\"] = request.{py_name}",
                            param.name
                        );
                    } else {
                        let _ = writeln!(output, "        if request.{py_name} is not None:");
                        let _ = writeln!(
                            output,
                            "            params[\"{}\"] = request.{py_name}",
                            param.name
                        );
                    }
                }
            }

            // Build json body
            let has_body = op.request_body.is_some();
            if has_body {
                output.push_str("        json_body = asdict(request.body) if hasattr(request.body, '__dataclass_fields__') else request.body\n");
            } else {
                output.push_str("        json_body = None\n");
            }

            // Make request
            let http_method = op
                .method
                .as_ref()
                .map_or_else(|| "GET".to_string(), |m| m.to_string().to_uppercase());

            let _ = writeln!(
                output,
                "        return self._request(\"{http_method}\", path, json=json_body, params=params)"
            );
            output.push('\n');
        }

        // Factory function
        let _ = writeln!(output, "\ndef create_{service_snake}_client(");
        output.push_str("    base_url: str,\n");
        output.push_str("    headers: Optional[dict[str, str]] = None,\n");
        output.push_str("    timeout: float = 30.0,\n");
        let _ = writeln!(output, ") -> {service_name}Client:");
        output.push_str(&format_docstring(
            &format!("Create a {} client.", contract.metadata.service_name),
            1,
        ));
        let _ = writeln!(
            output,
            "    return {service_name}Client(base_url, headers, timeout)"
        );

        Ok(output)
    }

    /// Builds a Python f-string path expression with parameter substitution.
    fn build_path_expression(&self, op: &Operation) -> String {
        let path = op.path.clone().unwrap_or_else(|| "/".to_string());

        // Check if there are path parameters
        let has_path_params = op
            .parameters
            .iter()
            .any(|p| p.location == ParameterLocation::Path);

        if !has_path_params {
            return format!("\"{}\"", path);
        }

        // Replace {param} with {request.param}
        let mut f_string = path;
        for param in &op.parameters {
            if param.location == ParameterLocation::Path {
                let placeholder = format!("{{{}}}", param.name);
                let py_expr = format!("{{request.{}}}", param.name.to_snake_case());
                f_string = f_string.replace(&placeholder, &py_expr);
            }
        }

        format!("f\"{f_string}\"")
    }

    /// Generates the FastAPI handlers file.
    fn generate_handlers_file(&self, contract: &Contract) -> CodegenResult<String> {
        let mut output = String::new();
        let service_name = contract.metadata.service_name.to_upper_camel_case();
        let service_snake = contract.metadata.service_name.to_snake_case();

        // Header
        output.push_str("# Auto-generated by themis-codegen. DO NOT EDIT.\n");
        let _ = writeln!(
            output,
            "# Contract: {} v{}\n",
            contract.metadata.service_name, contract.version
        );

        // Imports
        output.push_str("from __future__ import annotations\n\n");
        output.push_str("from abc import ABC, abstractmethod\n");
        output.push_str("from dataclasses import dataclass\n");
        output.push_str("from typing import Any, Optional, Protocol\n");
        output.push_str("from uuid import uuid4\n\n");
        output.push_str("from fastapi import APIRouter, Depends, HTTPException, Request\n\n");

        // Import types
        let _ = writeln!(output, "from .types import (");
        for (_, op) in &contract.operations {
            let request_type = format!("{}Request", op.operation_id.to_upper_camel_case());
            let response_type = format!("{}Response", op.operation_id.to_upper_camel_case());
            let _ = writeln!(output, "    {request_type},");
            let _ = writeln!(output, "    {response_type},");
        }
        output.push_str(")\n\n");

        // Request context
        output.push_str("@dataclass\n");
        output.push_str("class RequestContext:\n");
        output.push_str(&format_docstring("Context passed to handlers.", 1));
        output.push_str("    request_id: str\n");
        output.push_str("    user_id: Optional[str] = None\n");
        output.push_str("    headers: Optional[dict[str, str]] = None\n");
        output.push_str("\n\n");

        // Handlers Protocol (interface)
        let _ = writeln!(output, "class {service_name}Handlers(Protocol):");
        output.push_str(&format_docstring(
            &format!("Handler interface for {}.", contract.metadata.service_name),
            1,
        ));

        for (_, op) in &contract.operations {
            let method_name = op.operation_id.to_snake_case();
            let request_type = format!("{}Request", op.operation_id.to_upper_camel_case());
            let response_type = format!("{}Response", op.operation_id.to_upper_camel_case());

            if self.config.include_docs {
                if let Some(summary) = &op.summary {
                    let _ = writeln!(output, "    # {summary}");
                }
            }
            let _ = writeln!(
                output,
                "    def {method_name}(self, ctx: RequestContext, request: {request_type}) -> {response_type}: ..."
            );
        }
        output.push_str("\n\n");

        // Router factory function
        let _ = writeln!(output, "def create_{service_snake}_router(");
        let _ = writeln!(output, "    handlers: {service_name}Handlers,");
        output.push_str(") -> APIRouter:\n");
        output.push_str(&format_docstring(
            &format!(
                "Create a FastAPI router for {}.",
                contract.metadata.service_name
            ),
            1,
        ));
        output.push_str("    router = APIRouter()\n\n");

        // Helper to get request context
        output.push_str("    def get_context(request: Request) -> RequestContext:\n");
        output.push_str("        return RequestContext(\n");
        output.push_str(
            "            request_id=request.headers.get(\"X-Request-ID\", str(uuid4())),\n",
        );
        output.push_str("            user_id=getattr(request.state, \"user_id\", None),\n");
        output.push_str("            headers=dict(request.headers),\n");
        output.push_str("        )\n\n");

        // Generate route handlers
        for (_, op) in &contract.operations {
            let method_name = op.operation_id.to_snake_case();
            let request_type = format!("{}Request", op.operation_id.to_upper_camel_case());
            let response_type = format!("{}Response", op.operation_id.to_upper_camel_case());

            let http_method = op
                .method
                .as_ref()
                .map_or_else(|| "get".to_string(), |m| m.to_string().to_lowercase());
            let path =
                self.path_to_fastapi_format(&op.path.clone().unwrap_or_else(|| "/".to_string()));

            let _ = writeln!(output, "    @router.{http_method}(\"{path}\")");

            // Build function signature with parameters
            let _ = writeln!(output, "    async def {method_name}(");
            output.push_str("        request: Request,\n");

            // Path parameters
            for param in &op.parameters {
                if param.location == ParameterLocation::Path {
                    let py_name = param.name.to_snake_case();
                    let _ = writeln!(output, "        {py_name}: str,");
                }
            }

            // Query parameters
            for param in &op.parameters {
                if param.location == ParameterLocation::Query {
                    let py_name = param.name.to_snake_case();
                    if param.required {
                        let _ = writeln!(output, "        {py_name}: str,");
                    } else {
                        let _ = writeln!(output, "        {py_name}: Optional[str] = None,");
                    }
                }
            }

            // Request body
            if op.request_body.is_some() {
                output.push_str("        body: dict[str, Any],\n");
            }

            let _ = writeln!(output, "    ) -> {response_type}:");

            // Build request object
            output.push_str("        ctx = get_context(request)\n");
            let _ = writeln!(output, "        req = {request_type}(");

            // Path parameters
            for param in &op.parameters {
                if param.location == ParameterLocation::Path {
                    let py_name = param.name.to_snake_case();
                    let _ = writeln!(output, "            {py_name}={py_name},");
                }
            }

            // Query parameters
            for param in &op.parameters {
                if param.location == ParameterLocation::Query {
                    let py_name = param.name.to_snake_case();
                    let _ = writeln!(output, "            {py_name}={py_name},");
                }
            }

            // Body
            if op.request_body.is_some() {
                output.push_str("            body=body,\n");
            }

            output.push_str("        )\n");
            let _ = writeln!(output, "        return handlers.{method_name}(ctx, req)\n");
        }

        output.push_str("    return router\n");

        Ok(output)
    }

    /// Converts OpenAPI path to FastAPI format.
    fn path_to_fastapi_format(&self, path: &str) -> String {
        // FastAPI uses {param} same as OpenAPI, so no conversion needed
        path.to_string()
    }

    /// Generates the __init__.py file.
    fn generate_init_file(&self, contract: &Contract) -> String {
        let mut output = String::new();
        let service_name = contract.metadata.service_name.to_upper_camel_case();
        let service_snake = contract.metadata.service_name.to_snake_case();

        output.push_str("# Auto-generated by themis-codegen. DO NOT EDIT.\n\n");
        output.push_str("from .types import *\n");
        output.push_str("from .client import *\n");
        output.push_str("from .handlers import *\n\n");

        let _ = writeln!(output, "# Main exports");
        let _ = writeln!(output, "__all__ = [");
        let _ = writeln!(output, "    \"{service_name}Client\",");
        let _ = writeln!(output, "    \"create_{service_snake}_client\",");
        let _ = writeln!(output, "    \"{service_name}Handlers\",");
        let _ = writeln!(output, "    \"create_{service_snake}_router\",");
        let _ = writeln!(output, "    \"RequestContext\",");
        output.push_str("]\n");

        output
    }
}

impl CodeGenerator for PythonGenerator {
    fn language_name(&self) -> &'static str {
        "Python"
    }

    fn file_extension(&self) -> &'static str {
        "py"
    }

    fn generate(&self, contract: &Contract) -> CodegenResult<GeneratedCode> {
        if contract.operations.is_empty() {
            return Err(CodegenError::EmptyContract {
                name: contract.metadata.service_name.clone(),
            });
        }

        let mut output = GeneratedCode::new();

        // Generate types file
        let types_content = self.generate_types_file(contract)?;
        output.add_file(GeneratedFile::new("types.py", types_content));

        // Generate client file
        let client_content = self.generate_client_file(contract)?;
        output.add_file(GeneratedFile::new("client.py", client_content));

        // Generate handlers file
        let handlers_content = self.generate_handlers_file(contract)?;
        output.add_file(GeneratedFile::new("handlers.py", handlers_content));

        // Generate __init__.py
        let init_content = self.generate_init_file(contract);
        output.add_file(GeneratedFile::new("__init__.py", init_content));

        Ok(output)
    }

    fn config(&self) -> &GeneratorConfig {
        &self.config
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;
    use themis_core::contract::{ContractFormat, ContractMetadata};
    use themis_core::operation::{HttpMethod, MediaType, Parameter, RequestBody, Response};
    use themis_core::schema::{ObjectSchema, RefSchema, StringSchema};
    use themis_core::Schema;
    use themis_core::Version;

    fn create_test_contract() -> Contract {
        let mut schemas = HashMap::new();
        schemas.insert(
            "User".to_string(),
            Schema::Object(ObjectSchema {
                description: Some("A user in the system".to_string()),
                properties: {
                    let mut props = HashMap::new();
                    props.insert("id".to_string(), Schema::String(StringSchema::default()));
                    props.insert("email".to_string(), Schema::String(StringSchema::default()));
                    props.insert("name".to_string(), Schema::String(StringSchema::default()));
                    props
                },
                required: vec!["id".to_string(), "email".to_string()],
                additional_properties: None,
                nullable: false,
            }),
        );

        let mut operations = HashMap::new();

        // getUser operation
        let mut get_user = Operation::new("getUser");
        get_user.method = Some(HttpMethod::Get);
        get_user.path = Some("/users/{userId}".to_string());
        get_user.summary = Some("Get a user by ID".to_string());
        get_user.description = Some("Retrieves a user by their unique identifier".to_string());
        get_user.parameters = vec![Parameter {
            name: "userId".to_string(),
            location: ParameterLocation::Path,
            required: true,
            deprecated: false,
            schema: Schema::String(StringSchema::default()),
            description: Some("The user's ID".to_string()),
        }];
        get_user.responses.insert(
            "200".to_string(),
            Response {
                description: "Success".to_string(),
                content: {
                    let mut content = HashMap::new();
                    content.insert(
                        "application/json".to_string(),
                        MediaType {
                            schema: Schema::Ref(RefSchema {
                                reference: "#/components/schemas/User".to_string(),
                            }),
                        },
                    );
                    content
                },
                headers: HashMap::new(),
            },
        );
        operations.insert("getUser".to_string(), get_user);

        // createUser operation
        let mut create_user = Operation::new("createUser");
        create_user.method = Some(HttpMethod::Post);
        create_user.path = Some("/users".to_string());
        create_user.summary = Some("Create a new user".to_string());
        create_user.request_body = Some(RequestBody {
            description: None,
            required: true,
            content: {
                let mut content = HashMap::new();
                content.insert(
                    "application/json".to_string(),
                    MediaType {
                        schema: Schema::Object(ObjectSchema {
                            description: None,
                            properties: {
                                let mut props = HashMap::new();
                                props.insert(
                                    "email".to_string(),
                                    Schema::String(StringSchema::default()),
                                );
                                props.insert(
                                    "name".to_string(),
                                    Schema::String(StringSchema::default()),
                                );
                                props
                            },
                            required: vec!["email".to_string(), "name".to_string()],
                            additional_properties: None,
                            nullable: false,
                        }),
                    },
                );
                content
            },
        });
        create_user.responses.insert(
            "201".to_string(),
            Response {
                description: "Created".to_string(),
                content: {
                    let mut content = HashMap::new();
                    content.insert(
                        "application/json".to_string(),
                        MediaType {
                            schema: Schema::Ref(RefSchema {
                                reference: "#/components/schemas/User".to_string(),
                            }),
                        },
                    );
                    content
                },
                headers: HashMap::new(),
            },
        );
        operations.insert("createUser".to_string(), create_user);

        Contract {
            format: ContractFormat::OpenApi,
            version: Version::new(1, 0, 0),
            metadata: ContractMetadata {
                service_name: "users-service".to_string(),
                description: None,
                owner: None,
                repository: None,
                documentation_url: None,
            },
            schemas,
            operations,
            security_schemes: HashMap::new(),
        }
    }

    #[test]
    fn test_python_generator_language_name() {
        let config = GeneratorConfig::default();
        let generator = PythonGenerator::new(config);
        assert_eq!(generator.language_name(), "Python");
    }

    #[test]
    fn test_python_generator_file_extension() {
        let config = GeneratorConfig::default();
        let generator = PythonGenerator::new(config);
        assert_eq!(generator.file_extension(), "py");
    }

    #[test]
    fn test_python_generator_creates_files() {
        let config = GeneratorConfig::default();
        let generator = PythonGenerator::new(config);
        let contract = create_test_contract();

        let result = generator.generate(&contract).unwrap();

        assert!(result.get_file("types.py").is_some());
        assert!(result.get_file("client.py").is_some());
        assert!(result.get_file("handlers.py").is_some());
        assert!(result.get_file("__init__.py").is_some());
    }

    #[test]
    fn test_python_generator_types_content() {
        let config = GeneratorConfig::default();
        let generator = PythonGenerator::new(config);
        let contract = create_test_contract();

        let result = generator.generate(&contract).unwrap();
        let types_file = result.get_file("types.py").unwrap();

        assert!(types_file.content.contains("@dataclass"));
        assert!(types_file.content.contains("class User:"));
        assert!(types_file.content.contains("id: str"));
        assert!(types_file.content.contains("class GetUserRequest:"));
        assert!(types_file.content.contains("class CreateUserRequest:"));
    }

    #[test]
    fn test_python_generator_client_content() {
        let config = GeneratorConfig::default();
        let generator = PythonGenerator::new(config);
        let contract = create_test_contract();

        let result = generator.generate(&contract).unwrap();
        let client_file = result.get_file("client.py").unwrap();

        assert!(client_file.content.contains("class UsersServiceClient:"));
        assert!(client_file.content.contains("def get_user("));
        assert!(client_file.content.contains("def create_user("));
        assert!(client_file.content.contains("import httpx"));
        assert!(client_file
            .content
            .contains("def create_users_service_client"));
    }

    #[test]
    fn test_python_generator_handlers_content() {
        let config = GeneratorConfig::default();
        let generator = PythonGenerator::new(config);
        let contract = create_test_contract();

        let result = generator.generate(&contract).unwrap();
        let handlers_file = result.get_file("handlers.py").unwrap();

        assert!(handlers_file.content.contains("class RequestContext:"));
        assert!(handlers_file
            .content
            .contains("class UsersServiceHandlers(Protocol):"));
        assert!(handlers_file
            .content
            .contains("def create_users_service_router"));
        assert!(handlers_file.content.contains("from fastapi import"));
        assert!(handlers_file
            .content
            .contains("@router.get(\"/users/{userId}\")"));
        assert!(handlers_file.content.contains("@router.post(\"/users\")"));
    }

    #[test]
    fn test_python_generator_empty_contract_fails() {
        let config = GeneratorConfig::default();
        let generator = PythonGenerator::new(config);
        let contract = Contract {
            format: ContractFormat::OpenApi,
            version: Version::new(1, 0, 0),
            metadata: ContractMetadata {
                service_name: "empty-service".to_string(),
                description: None,
                owner: None,
                repository: None,
                documentation_url: None,
            },
            schemas: HashMap::new(),
            operations: HashMap::new(),
            security_schemes: HashMap::new(),
        };

        let result = generator.generate(&contract);
        assert!(result.is_err());
    }

    #[test]
    fn test_path_to_fastapi_format() {
        let config = GeneratorConfig::default();
        let generator = PythonGenerator::new(config);

        assert_eq!(
            generator.path_to_fastapi_format("/users/{userId}"),
            "/users/{userId}"
        );
    }

    #[test]
    fn test_build_path_expression() {
        let config = GeneratorConfig::default();
        let generator = PythonGenerator::new(config);

        let mut op = Operation::new("getUser");
        op.method = Some(HttpMethod::Get);
        op.path = Some("/users/{userId}".to_string());
        op.parameters = vec![Parameter {
            name: "userId".to_string(),
            location: ParameterLocation::Path,
            required: true,
            deprecated: false,
            schema: Schema::String(StringSchema::default()),
            description: None,
        }];

        let result = generator.build_path_expression(&op);
        assert_eq!(result, "f\"/users/{request.user_id}\"");
    }

    #[test]
    fn test_python_generator_with_docstrings() {
        let config = GeneratorConfig {
            include_docs: true,
            ..Default::default()
        };
        let generator = PythonGenerator::new(config);
        let contract = create_test_contract();

        let result = generator.generate(&contract).unwrap();
        let types_file = result.get_file("types.py").unwrap();

        // Should contain docstrings
        assert!(types_file
            .content
            .contains("\"\"\"A user in the system\"\"\""));
    }

    #[test]
    fn test_python_generator_init_file() {
        let config = GeneratorConfig::default();
        let generator = PythonGenerator::new(config);
        let contract = create_test_contract();

        let result = generator.generate(&contract).unwrap();
        let init_file = result.get_file("__init__.py").unwrap();

        assert!(init_file.content.contains("from .types import *"));
        assert!(init_file.content.contains("from .client import *"));
        assert!(init_file.content.contains("from .handlers import *"));
        assert!(init_file.content.contains("__all__"));
        assert!(init_file.content.contains("UsersServiceClient"));
        assert!(init_file.content.contains("create_users_service_client"));
    }
}
