//! Common traits for code generators.

use crate::config::GeneratorConfig;
use crate::error::CodegenResult;
use themis_core::Contract;

/// A file generated by a code generator.
#[derive(Debug, Clone)]
pub struct GeneratedFile {
    /// The relative path for this file.
    pub path: String,
    /// The content of the file.
    pub content: String,
    /// Whether this file should be overwritten if it exists.
    pub overwrite: bool,
}

impl GeneratedFile {
    /// Creates a new generated file.
    pub fn new(path: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            content: content.into(),
            overwrite: true,
        }
    }

    /// Creates a generated file that should not be overwritten.
    pub fn new_no_overwrite(path: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            content: content.into(),
            overwrite: false,
        }
    }
}

/// The output of a code generator.
#[derive(Debug, Clone, Default)]
pub struct GeneratedCode {
    /// Generated files.
    pub files: Vec<GeneratedFile>,
    /// Warning messages generated during code generation.
    pub warnings: Vec<String>,
}

impl GeneratedCode {
    /// Creates a new empty generated code output.
    pub const fn new() -> Self {
        Self {
            files: Vec::new(),
            warnings: Vec::new(),
        }
    }

    /// Adds a file to the output.
    pub fn add_file(&mut self, file: GeneratedFile) {
        self.files.push(file);
    }

    /// Adds a warning message.
    pub fn add_warning(&mut self, warning: impl Into<String>) {
        self.warnings.push(warning.into());
    }

    /// Merges another generated code output into this one.
    pub fn merge(&mut self, other: Self) {
        self.files.extend(other.files);
        self.warnings.extend(other.warnings);
    }

    /// Returns whether any files were generated.
    pub const fn has_files(&self) -> bool {
        !self.files.is_empty()
    }

    /// Returns whether there are any warnings.
    pub const fn has_warnings(&self) -> bool {
        !self.warnings.is_empty()
    }

    /// Gets a file by path.
    pub fn get_file(&self, path: &str) -> Option<&GeneratedFile> {
        self.files.iter().find(|f| f.path == path)
    }
}

/// Trait for code generators.
///
/// Implement this trait to create a code generator for a specific language.
pub trait CodeGenerator {
    /// Returns the name of the target language.
    fn language_name(&self) -> &'static str;

    /// Returns the file extension for generated files.
    fn file_extension(&self) -> &'static str;

    /// Generates code from a contract.
    fn generate(&self, contract: &Contract) -> CodegenResult<GeneratedCode>;

    /// Returns the configuration for this generator.
    fn config(&self) -> &GeneratorConfig;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generated_file_new() {
        let file = GeneratedFile::new("types.rs", "pub struct User {}");
        assert_eq!(file.path, "types.rs");
        assert_eq!(file.content, "pub struct User {}");
        assert!(file.overwrite);
    }

    #[test]
    fn test_generated_file_no_overwrite() {
        let file = GeneratedFile::new_no_overwrite("mod.rs", "mod types;");
        assert_eq!(file.path, "mod.rs");
        assert!(!file.overwrite);
    }

    #[test]
    fn test_generated_code_merge() {
        let mut code1 = GeneratedCode::new();
        code1.add_file(GeneratedFile::new("a.rs", "// a"));
        code1.add_warning("warning 1");

        let mut code2 = GeneratedCode::new();
        code2.add_file(GeneratedFile::new("b.rs", "// b"));
        code2.add_warning("warning 2");

        code1.merge(code2);
        assert_eq!(code1.files.len(), 2);
        assert_eq!(code1.warnings.len(), 2);
    }

    #[test]
    fn test_generated_code_get_file() {
        let mut code = GeneratedCode::new();
        code.add_file(GeneratedFile::new("types.rs", "content"));

        assert!(code.get_file("types.rs").is_some());
        assert!(code.get_file("missing.rs").is_none());
    }
}
